import { defineTools, IN, OUT } from "./shared";

export const audioTools = defineTools([
  {
    id: "audio-record",
    name: "Enregistrer au micro",
    description: "Capturer un son depuis le microphone et l'enregistrer localement.",
    category: "audio",
    icon: "Mic",
    keywords: ["enregistrer", "micro", "dictaphone", "capturer ma voix", "mémo vocal"],
    aliases: ["record audio", "voice recorder"],
    capabilities: ["local", "produces-files", "needs-device"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.audio(["wav", "mp3"])],
  },
  {
    id: "audio-trim",
    name: "Découper un audio",
    description: "Garder un extrait précis d'un fichier audio.",
    category: "audio",
    icon: "Scissors",
    keywords: ["découper", "couper", "extrait", "raccourcir", "rogner", "garder un passage"],
    aliases: ["trim audio", "cut audio", "split audio"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-merge",
    name: "Fusionner des audios",
    description: "Mettre plusieurs pistes bout à bout en un seul fichier.",
    category: "audio",
    icon: "Combine",
    keywords: ["fusionner", "assembler", "coller", "bout à bout", "réunir des pistes"],
    aliases: ["merge audio", "join audio", "concat audio"],
    capabilities: ["local", "batch", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio(true)],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-convert",
    name: "Convertir un audio",
    description: "Passer d'un format à un autre : MP3, WAV, FLAC, OGG, M4A, OPUS.",
    category: "audio",
    alsoIn: ["converters"],
    icon: "Repeat",
    keywords: [
      "convertir", "changer de format", "wav en mp3", "mp3 en wav",
      "flac", "ogg", "m4a", "opus", "aac",
    ],
    aliases: ["convert audio", "wav to mp3", "audio converter"],
    capabilities: ["local", "batch", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio(true)],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-compress",
    name: "Compresser un audio",
    description: "Réduire le poids d'un fichier audio en ajustant le débit.",
    category: "audio",
    icon: "Minimize2",
    keywords: ["compresser", "réduire la taille", "alléger", "bitrate", "débit", "trop lourd"],
    aliases: ["compress audio", "reduce audio size"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-volume",
    name: "Régler le volume",
    description: "Augmenter ou diminuer le volume global d'un fichier audio.",
    category: "audio",
    icon: "Volume2",
    keywords: ["volume", "plus fort", "moins fort", "amplifier", "baisser le son", "trop faible"],
    aliases: ["change volume", "amplify audio"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-normalize",
    name: "Normaliser un audio",
    description: "Uniformiser le niveau sonore de plusieurs fichiers (loudness).",
    category: "audio",
    icon: "AudioWaveform",
    keywords: ["normaliser", "uniformiser", "loudness", "même volume", "lufs", "égaliser le son"],
    aliases: ["normalize audio", "loudness"],
    capabilities: ["local", "batch", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio(true)],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-speed",
    name: "Changer la vitesse",
    description: "Accélérer ou ralentir un audio, avec ou sans correction de hauteur.",
    category: "audio",
    icon: "Gauge",
    keywords: ["vitesse", "accélérer", "ralentir", "tempo", "pitch", "plus rapide"],
    aliases: ["audio speed", "speed up audio", "slow down audio"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-remove-silence",
    name: "Supprimer les silences",
    description: "Détecter et couper automatiquement les blancs d'un enregistrement.",
    category: "audio",
    icon: "AudioLines",
    keywords: ["silences", "blancs", "couper les pauses", "nettoyer un enregistrement", "podcast"],
    aliases: ["remove silence", "trim silence"],
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
  },
  {
    id: "video-extract-audio",
    name: "Extraire l'audio d'une vidéo",
    description: "Récupérer la bande son d'une vidéo au format de votre choix.",
    category: "audio",
    alsoIn: ["video", "converters"],
    icon: "FileAudio",
    keywords: [
      "extraire le son", "bande son", "vidéo en mp3", "mp4 en mp3",
      "récupérer l'audio", "son d'une vidéo",
    ],
    aliases: ["extract audio", "video to mp3", "mp4 to mp3"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.audio()],
  },
  {
    id: "audio-transcribe",
    name: "Transcription audio",
    description: "Convertir la parole d'un fichier audio ou vidéo en texte, localement.",
    category: "audio",
    alsoIn: ["text", "video"],
    icon: "Captions",
    keywords: [
      "transcrire", "transcription", "audio en texte", "speech to text",
      "retranscrire", "réunion", "interview", "dicter", "sous-titrer",
      "transcrire mp3", "transcrire une vidéo",
    ],
    aliases: ["transcribe", "speech to text", "audio to text", "stt"],
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.audio(), IN.video()],
    outputs: [OUT.text(["txt", "srt", "vtt"])],
    note: "Modèle de reconnaissance vocale exécuté sur votre machine, installé à la demande.",
  },
  {
    id: "audio-generate-srt",
    name: "Générer des sous-titres SRT",
    description: "Produire un fichier de sous-titres horodaté depuis un audio ou une vidéo.",
    category: "audio",
    alsoIn: ["video", "text"],
    icon: "Subtitles",
    keywords: ["srt", "sous-titres", "vtt", "horodatage", "captions", "générer des sous-titres", "faire des sous titres"],
    aliases: ["generate subtitles", "srt generator"],
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.audio(), IN.video()],
    outputs: [OUT.text(["srt", "vtt"])],
  },
  {
    id: "text-to-speech",
    name: "Texte vers parole",
    description: "Lire un texte à voix haute et l'enregistrer en fichier audio, sans service en ligne.",
    category: "audio",
    alsoIn: ["text"],
    icon: "Speech",
    keywords: [
      "synthèse vocale", "tts", "lire à voix haute", "texte en audio",
      "voix de synthèse", "écouter un texte", "vocaliser",
      "lire un texte à voix haute", "faire un mp3 avec mon texte",
    ],
    aliases: ["text to speech", "tts", "synthèse vocale"],
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.text(), IN.none()],
    outputs: [OUT.audio(["wav", "mp3"])],
  },
  {
    id: "pdf-to-audio",
    name: "PDF vers audio",
    description: "Transformer un PDF en livre audio grâce à la synthèse vocale locale.",
    category: "audio",
    alsoIn: ["pdf", "converters"],
    icon: "Headphones",
    keywords: ["pdf en audio", "livre audio", "écouter un pdf", "lire mon pdf", "audiobook", "écouter un cours"],
    aliases: ["pdf to audio", "pdf to speech", "audiobook"],
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.audio(["mp3", "wav"])],
  },
  {
    id: "text-file-to-audio",
    name: "Fichier texte vers audio",
    description: "Convertir un fichier TXT ou Markdown en fichier audio narré.",
    category: "audio",
    alsoIn: ["text", "converters"],
    icon: "BookAudio",
    keywords: ["txt en audio", "livre audio", "narration", "écouter un texte", "faire un mp3 avec mon texte"],
    aliases: ["txt to audio", "text file to audio"],
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [{ kind: "text", extensions: ["txt", "md"], multiple: false }],
    outputs: [OUT.audio(["mp3", "wav"])],
  },
  {
    id: "audio-channels",
    name: "Convertir les canaux audio",
    description:
      "Passer un fichier en mono ou en stéréo, ou le laisser tel quel. Un fichier multicanal n'est jamais réduit sans qu'on le demande.",
    category: "audio",
    icon: "AudioLines",
    keywords: [
      "mono stereo", "canaux audio", "mono", "stereo", "passer en mono",
      "passer en stereo", "downmix", "melanger les canaux", "5.1 en stereo",
      "un seul canal", "deux canaux",
    ],
    aliases: ["audio channels", "mono to stereo", "stereo to mono", "downmix"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
    note: "Du mono vers le stéréo, le canal est dupliqué : les deux voies portent le même signal. Aucune spatialisation n'est fabriquée.",
  },
  {
    id: "audio-metadata",
    name: "Modifier les étiquettes audio",
    description:
      "Lire et corriger titre, artiste, album, année, genre, piste et commentaire — sans réencoder le son.",
    category: "audio",
    icon: "Tags",
    keywords: [
      "metadata audio", "metadonnees audio", "etiquettes", "tags mp3", "id3",
      "titre artiste album", "renommer les tags", "corriger un titre",
      "annee genre piste", "modifier les informations d'un mp3",
    ],
    aliases: ["audio metadata", "id3 tags", "edit tags", "music tags"],
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.audio()],
    outputs: [OUT.audio()],
    note: "L'écriture recopie le flux audio tel quel (-c copy) : le son produit est identique au bit près.",
  },
  {
    id: "media-info",
    name: "Inspecter un média",
    description:
      "Tout ce qu'un fichier audio ou vidéo déclare : conteneur, codecs, résolution, cadence, débits, canaux, étiquettes.",
    category: "audio",
    alsoIn: ["video", "files"],
    icon: "FileSearch",
    keywords: [
      "metadata video", "metadata audio", "metadonnees", "informations media",
      "codec", "bitrate", "debit", "resolution video", "frequence d'images",
      "fps video", "canaux", "echantillonnage", "inspecter une video",
      "proprietes d'un fichier video", "ffprobe",
    ],
    aliases: ["media info", "media metadata", "video metadata", "audio metadata", "ffprobe", "mediainfo"],
    capabilities: ["local", "needs-sidecar"],
    acceptedInputs: [
      { kind: "audio", extensions: ["mp3", "wav", "flac", "ogg", "m4a", "aac", "opus"], multiple: false },
      { kind: "video", extensions: ["mp4", "mkv", "webm", "mov", "avi", "gif"], multiple: false },
    ],
    outputs: [OUT.none()],
  },
]);
