import { defineTools, IN, OUT } from "./shared";

export const developerTools = defineTools([
  {
    id: "json-tools",
    name: "JSON — formater et valider",
    description: "Indenter, minifier et vérifier la validité d'un JSON, avec message d'erreur précis.",
    category: "developer",
    icon: "Braces",
    keywords: ["json", "formater", "indenter", "valider", "prettify", "minifier", "parser"],
    aliases: ["json formatter", "json validator", "json beautifier", "prettify json"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "data", extensions: ["json"] }],
    outputs: [OUT.text(["json"])],
  },
  {
    id: "xml-format",
    name: "XML — formater",
    description: "Indenter et valider un document XML.",
    category: "developer",
    icon: "Code2",
    keywords: ["xml", "formater", "indenter", "valider", "balises"],
    aliases: ["xml formatter", "xml beautifier"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "data", extensions: ["xml"] }],
    outputs: [OUT.text(["xml"])],
  },
  {
    id: "yaml-format",
    name: "YAML — formater et convertir",
    description: "Formater du YAML et le convertir depuis ou vers JSON.",
    category: "developer",
    alsoIn: ["converters"],
    icon: "FileCode2",
    keywords: ["yaml", "yml", "formater", "yaml en json", "json en yaml", "configuration"],
    aliases: ["yaml formatter", "yaml to json", "json to yaml"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "data", extensions: ["yaml", "yml", "json"] }],
    outputs: [OUT.text(["yaml", "json"])],
  },
  {
    id: "sql-format",
    name: "SQL — formater",
    description: "Rendre lisible une requête SQL compacte ou générée.",
    category: "developer",
    icon: "Database",
    keywords: ["sql", "requête", "formater", "indenter", "lisible", "query"],
    aliases: ["sql formatter", "sql beautifier"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "data", extensions: ["sql"] }],
    outputs: [OUT.text(["sql"])],
  },
  {
    id: "base64",
    name: "Base64 — encoder et décoder",
    description: "Convertir du texte en Base64 et inversement, y compris en base64url.",
    category: "developer",
    icon: "Binary",
    keywords: ["base64", "encoder", "décoder", "b64", "encodage", "data uri"],
    aliases: ["base64 encode", "base64 decode", "b64"],
    status: "available",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "url-encode",
    name: "URL — encoder et décoder",
    description: "Encoder ou décoder une URL et ses paramètres (percent-encoding).",
    category: "developer",
    icon: "Link2",
    keywords: ["url", "encoder", "décoder", "percent encoding", "querystring", "caractères spéciaux"],
    aliases: ["url encode", "url decode", "uri encode"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "jwt-decode",
    name: "JWT — décoder",
    description: "Lire l'en-tête et la charge utile d'un token JWT, sans l'envoyer nulle part.",
    category: "developer",
    alsoIn: ["security"],
    icon: "KeyRound",
    keywords: ["jwt", "token", "décoder", "bearer", "payload", "claims"],
    aliases: ["jwt decoder", "decode token"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
    note: "Le token est décodé localement : il ne quitte jamais votre machine.",
  },
  {
    id: "uuid-generate",
    name: "Générer des UUID",
    description: "Produire des identifiants uniques v4 ou v7, à l'unité ou par lots.",
    category: "developer",
    icon: "Hash",
    keywords: ["uuid", "guid", "identifiant unique", "générer un id", "v4", "v7"],
    aliases: ["uuid generator", "guid generator"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "regex-tester",
    name: "Testeur d'expressions régulières",
    description: "Tester une regex en direct, voir les correspondances et les groupes.",
    category: "developer",
    icon: "Regex",
    keywords: ["regex", "expression régulière", "tester", "correspondance", "pattern", "match"],
    aliases: ["regex tester", "regexp", "regex101"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "timestamp-convert",
    name: "Timestamp Unix",
    description: "Convertir un timestamp en date lisible et inversement, avec fuseaux horaires.",
    category: "developer",
    alsoIn: ["calculators"],
    icon: "Clock",
    keywords: ["timestamp", "unix", "epoch", "date en secondes", "millisecondes", "convertir une date"],
    aliases: ["unix timestamp", "epoch converter"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "hash-text",
    name: "Générer un hash de texte",
    description: "Calculer MD5, SHA-1, SHA-256 ou SHA-512 d'une chaîne de caractères.",
    category: "developer",
    alsoIn: ["security"],
    icon: "Fingerprint",
    keywords: ["hash", "md5", "sha256", "empreinte", "hacher un texte", "digest"],
    aliases: ["hash generator", "md5 text", "sha256 text"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "qr-generate",
    name: "Générer un QR Code",
    description: "Créer un QR code pour une URL, un texte, un contact ou un réseau Wi-Fi.",
    category: "developer",
    alsoIn: ["images"],
    icon: "QrCode",
    keywords: ["qr code", "qrcode", "code barre", "générer un qr", "wifi", "vcard"],
    aliases: ["qr code generator", "make qr code"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.image(["png", "svg"])],
  },
  {
    id: "qr-read",
    name: "Lire un QR Code",
    description: "Décoder un QR code depuis une image ou une capture d'écran.",
    category: "developer",
    alsoIn: ["images"],
    icon: "ScanLine",
    keywords: ["lire un qr", "scanner", "décoder un qr code", "qr depuis une image"],
    aliases: ["qr code reader", "scan qr code", "decode qr"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.none()],
  },
  {
    id: "number-base-convert",
    name: "Convertir HEX, décimal, binaire",
    description: "Passer d'une base à l'autre : binaire, octal, décimal, hexadécimal.",
    category: "developer",
    alsoIn: ["calculators", "converters"],
    icon: "Binary",
    keywords: ["hexadécimal", "binaire", "décimal", "octal", "base 16", "base 2", "convertir un nombre"],
    aliases: ["hex to decimal", "binary converter", "base converter"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "code-diff",
    name: "Diff de code",
    description: "Comparer deux blocs de code avec coloration des ajouts et suppressions.",
    category: "developer",
    icon: "GitCompare",
    keywords: ["diff", "comparer du code", "différences", "merge", "versions"],
    aliases: ["code diff", "compare code"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "web-minify",
    name: "Minifier HTML, CSS, JS",
    description: "Réduire la taille du code en supprimant espaces et commentaires.",
    category: "developer",
    icon: "Minimize2",
    keywords: ["minifier", "compresser du code", "réduire", "uglify", "production"],
    aliases: ["minify", "minify css", "minify js", "minify html"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "text", extensions: ["html", "css", "js"] }],
    outputs: [OUT.text(["html", "css", "js"])],
  },
  {
    id: "web-beautify",
    name: "Formater HTML, CSS, JS",
    description: "Réindenter du code minifié ou mal formaté pour le rendre lisible.",
    category: "developer",
    icon: "Braces",
    keywords: ["formater", "indenter", "beautify", "prettify", "code illisible", "réindenter"],
    aliases: ["beautify", "format code", "prettify html"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "text", extensions: ["html", "css", "js"] }],
    outputs: [OUT.text(["html", "css", "js"])],
  },
  {
    id: "cron-helper",
    name: "Assistant cron",
    description: "Construire et expliquer une expression cron en langage clair.",
    category: "developer",
    icon: "CalendarClock",
    keywords: ["cron", "crontab", "planification", "tâche planifiée", "expression cron", "schedule"],
    aliases: ["cron generator", "crontab helper", "cron expression"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
]);
