import { defineTools, IN, OUT } from "./shared";

export const fileTools = defineTools([
  {
    id: "archive-create",
    name: "Créer une archive",
    description: "Compresser des fichiers ou dossiers en ZIP, TAR ou TAR.GZ, arborescence conservée.",
    category: "files",
    icon: "FolderArchive",
    keywords: [
      "zip", "compresser", "archiver", "7z", "tar", "tar.gz",
      "mettre dans un zip", "regrouper des fichiers",
    ],
    aliases: ["create zip", "compress files", "make archive"],
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.archive(["zip", "tar", "gz"])],
    note: "Le format 7z n'est pas proposé : aucune bibliothèque 7z n'est disponible en Rust avec une maturité et une licence compatibles, et un binaire externe casserait la promesse « tout est embarqué ».",
  },
  {
    id: "archive-extract",
    name: "Extraire une archive",
    description: "Décompresser une archive ZIP, TAR ou TAR.GZ vers le dossier de votre choix.",
    category: "files",
    icon: "PackageOpen",
    keywords: ["dézipper", "décompresser", "extraire", "ouvrir un zip", "unzip", "désarchiver"],
    aliases: ["unzip", "extract archive", "decompress"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [{ kind: "archive", extensions: ["zip", "tar", "gz", "tgz"] }],
    outputs: [OUT.data()],
    note: "Aucun fichier n'est écrit hors du dossier choisi : les entrées dont le chemin remonte (« ../ »), les chemins absolus et les liens symboliques sont refusés et listés. Les formats 7z et RAR ne sont pas pris en charge.",
  },
  {
    id: "archive-encrypted",
    name: "Archive protégée par mot de passe",
    description: "Créer ou ouvrir une archive chiffrée par mot de passe.",
    category: "files",
    alsoIn: ["security"],
    icon: "FileLock2",
    keywords: [
      "archive protégée", "zip avec mot de passe", "7z chiffré",
      "protéger des fichiers", "archive sécurisée",
    ],
    aliases: ["encrypted zip", "password protected archive"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(), IN.archive()],
    outputs: [OUT.archive()],
    note: "Non disponible : le chiffrement historique du ZIP (ZipCrypto) est cassable en quelques secondes, et proposer une « archive protégée » qui ne protège pas serait trompeur. L'AES-256 du ZIP demande une brique de chiffrement supplémentaire, prévue avec les outils de chiffrement de fichiers.",
  },
  {
    id: "file-hash",
    name: "Calculer une empreinte (hash)",
    description: "Obtenir le SHA-256, SHA-512, SHA-1 ou MD5 d'un ou plusieurs fichiers, quelle que soit leur taille.",
    category: "files",
    alsoIn: ["security", "developer"],
    icon: "Fingerprint",
    keywords: ["hash", "empreinte", "md5", "sha256", "sha1", "checksum", "somme de contrôle"],
    aliases: ["file hash", "checksum", "md5", "sha256"],
    capabilities: ["local", "batch", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
  },
  {
    id: "file-verify-hash",
    name: "Vérifier une empreinte",
    description: "Comparer l'empreinte d'un fichier à celle annoncée par sa source.",
    category: "files",
    alsoIn: ["security"],
    icon: "BadgeCheck",
    keywords: [
      "vérifier", "intégrité", "checksum", "le fichier est-il corrompu",
      "comparer un hash", "authenticité",
    ],
    aliases: ["verify checksum", "check integrity", "hash compare"],
    capabilities: ["local"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.none()],
  },
  {
    id: "file-find-duplicates",
    name: "Trouver les fichiers en double",
    description: "Détecter les doublons d'un dossier par contenu et non par nom.",
    category: "files",
    icon: "CopyMinus",
    keywords: ["doublons", "fichiers identiques", "gagner de la place", "nettoyer", "photos en double"],
    aliases: ["find duplicates", "duplicate finder"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-compare",
    name: "Comparer deux fichiers",
    description: "Vérifier si deux fichiers sont identiques, octet par octet ou ligne par ligne.",
    category: "files",
    icon: "GitCompare",
    keywords: ["comparer", "identiques", "différences", "binaire", "diff de fichiers"],
    aliases: ["compare files", "file diff"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
  },
  {
    id: "file-bulk-rename",
    name: "Renommage en masse",
    description: "Renommer des centaines de fichiers avec un modèle, une numérotation ou une regex.",
    category: "files",
    icon: "PenLine",
    keywords: [
      "renommer", "en masse", "batch rename", "numéroter les fichiers",
      "préfixe", "suffixe", "tous mes fichiers",
    ],
    aliases: ["bulk rename", "batch rename"],
    capabilities: ["local", "batch", "destructive"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-clean-names",
    name: "Nettoyer les noms de fichiers",
    description: "Retirer accents, espaces et caractères problématiques des noms de fichiers.",
    category: "files",
    icon: "Eraser",
    keywords: ["accents", "espaces dans les noms", "caractères spéciaux", "slug", "normaliser"],
    aliases: ["clean filenames", "sanitize filenames"],
    capabilities: ["local", "batch", "destructive"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-organize",
    name: "Organiser un dossier",
    description: "Ranger automatiquement les fichiers par extension, par date ou par type.",
    category: "files",
    icon: "FolderTree",
    keywords: [
      "ranger", "organiser", "classer", "par extension", "par date",
      "trier mon dossier téléchargements", "mettre de l'ordre",
    ],
    aliases: ["organize folder", "sort files"],
    capabilities: ["local", "batch", "long-running", "destructive"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "folder-size",
    name: "Analyser la taille d'un dossier",
    description: "Voir ce qui occupe réellement l'espace disque, dossier par dossier.",
    category: "files",
    icon: "HardDrive",
    keywords: [
      "taille", "espace disque", "qu'est-ce qui prend de la place",
      "gros fichiers", "disque plein", "analyser",
    ],
    aliases: ["folder size", "disk usage", "disk analyzer"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-secure-delete",
    name: "Suppression sécurisée",
    description: "Écraser le contenu d'un fichier avant de le supprimer, pour rendre sa récupération logicielle très improbable.",
    category: "files",
    alsoIn: ["security"],
    icon: "Trash2",
    keywords: [
      "effacer définitivement", "suppression sécurisée", "irrécupérable",
      "shred", "détruire un fichier", "vraiment supprimer",
    ],
    aliases: ["secure delete", "shred", "wipe file"],
    capabilities: ["local", "destructive", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
    note: "Effacement logiciel renforcé, pas effacement physique : sur SSD, carte mémoire, Btrfs/ZFS/APFS, ou en présence d'instantanés et de sauvegardes, aucun logiciel ne peut garantir la disparition de toutes les copies antérieures.",
  },
  {
    id: "file-split",
    name: "Diviser un gros fichier",
    description: "Découper un fichier volumineux en morceaux numérotés, avec manifeste de vérification.",
    category: "files",
    icon: "Scissors",
    keywords: [
      "diviser", "découper", "split", "morceaux", "fichier trop gros",
      "clé usb", "fat32", "envoyer un gros fichier", "part001",
    ],
    aliases: ["split file", "file splitter", "diviser un fichier"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.data()],
  },
  {
    id: "file-join",
    name: "Réassembler un fichier",
    description: "Reconstituer un fichier à partir de ses morceaux .part001, avec vérification d'empreinte.",
    category: "files",
    icon: "Combine",
    keywords: [
      "réassembler", "recoller", "join", "fusionner des morceaux",
      "part001", "reconstituer un fichier", "remettre ensemble",
    ],
    aliases: ["join files", "merge parts", "reassemble"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.data()],
  },
  {
    id: "folder-tree",
    name: "Générer l'arborescence d'un dossier",
    description: "Produire l'arborescence en texte d'un dossier, prête à coller dans un README.",
    category: "files",
    alsoIn: ["developer"],
    icon: "FolderTree",
    keywords: [
      "arborescence", "structure", "tree", "plan du dossier",
      "hiérarchie", "readme", "liste des dossiers",
    ],
    aliases: ["folder tree", "directory tree", "arbre des dossiers"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.text()],
  },
  {
    id: "file-info",
    name: "Informations sur un fichier",
    description: "Taille, dates, type MIME, type réel détecté et empreinte SHA-256 d'un fichier.",
    category: "files",
    alsoIn: ["security"],
    icon: "FileSearch",
    keywords: [
      "informations", "propriétés", "détails", "type de fichier",
      "quel format", "mime", "date de création", "c'est quoi ce fichier",
    ],
    aliases: ["file info", "file properties", "file details"],
    capabilities: ["local"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.none()],
  },
]);
