import { defineTools, IN, OUT } from "./shared";

export const fileTools = defineTools([
  {
    id: "archive-create",
    name: "Créer une archive",
    description: "Compresser des fichiers ou dossiers en ZIP, 7z, TAR ou TAR.GZ.",
    category: "files",
    icon: "FolderArchive",
    keywords: [
      "zip", "compresser", "archiver", "7z", "tar", "tar.gz",
      "mettre dans un zip", "regrouper des fichiers",
    ],
    aliases: ["create zip", "compress files", "make archive"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.archive()],
  },
  {
    id: "archive-extract",
    name: "Extraire une archive",
    description: "Décompresser ZIP, 7z, TAR, GZ, RAR vers le dossier de votre choix.",
    category: "files",
    icon: "PackageOpen",
    keywords: ["dézipper", "décompresser", "extraire", "ouvrir un zip", "unzip", "désarchiver"],
    aliases: ["unzip", "extract archive", "decompress"],
    status: "planned",
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.archive()],
    outputs: [OUT.data()],
  },
  {
    id: "archive-encrypted",
    name: "Archive protégée par mot de passe",
    description: "Créer ou ouvrir une archive chiffrée par mot de passe.",
    category: "files",
    alsoIn: ["security"],
    icon: "FileLock2",
    keywords: [
      "archive protégée", "zip avec mot de passe", "7z chiffré",
      "protéger des fichiers", "archive sécurisée",
    ],
    aliases: ["encrypted zip", "password protected archive"],
    status: "planned",
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(), IN.archive()],
    outputs: [OUT.archive()],
  },
  {
    id: "file-hash",
    name: "Calculer une empreinte (hash)",
    description: "Obtenir le MD5, SHA-1, SHA-256 ou SHA-512 d'un ou plusieurs fichiers.",
    category: "files",
    alsoIn: ["security", "developer"],
    icon: "Fingerprint",
    keywords: ["hash", "empreinte", "md5", "sha256", "sha1", "checksum", "somme de contrôle"],
    aliases: ["file hash", "checksum", "md5", "sha256"],
    status: "planned",
    capabilities: ["local", "batch", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
  },
  {
    id: "file-verify-hash",
    name: "Vérifier une empreinte",
    description: "Comparer l'empreinte d'un fichier à celle annoncée par sa source.",
    category: "files",
    alsoIn: ["security"],
    icon: "BadgeCheck",
    keywords: [
      "vérifier", "intégrité", "checksum", "le fichier est-il corrompu",
      "comparer un hash", "authenticité",
    ],
    aliases: ["verify checksum", "check integrity", "hash compare"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.none()],
  },
  {
    id: "file-find-duplicates",
    name: "Trouver les fichiers en double",
    description: "Détecter les doublons d'un dossier par contenu et non par nom.",
    category: "files",
    icon: "CopyMinus",
    keywords: ["doublons", "fichiers identiques", "gagner de la place", "nettoyer", "photos en double"],
    aliases: ["find duplicates", "duplicate finder"],
    status: "planned",
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-compare",
    name: "Comparer deux fichiers",
    description: "Vérifier si deux fichiers sont identiques, octet par octet ou ligne par ligne.",
    category: "files",
    icon: "GitCompare",
    keywords: ["comparer", "identiques", "différences", "binaire", "diff de fichiers"],
    aliases: ["compare files", "file diff"],
    status: "planned",
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
  },
  {
    id: "file-bulk-rename",
    name: "Renommage en masse",
    description: "Renommer des centaines de fichiers avec un modèle, une numérotation ou une regex.",
    category: "files",
    icon: "PenLine",
    keywords: [
      "renommer", "en masse", "batch rename", "numéroter les fichiers",
      "préfixe", "suffixe", "tous mes fichiers",
    ],
    aliases: ["bulk rename", "batch rename"],
    status: "planned",
    capabilities: ["local", "batch", "destructive"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-clean-names",
    name: "Nettoyer les noms de fichiers",
    description: "Retirer accents, espaces et caractères problématiques des noms de fichiers.",
    category: "files",
    icon: "Eraser",
    keywords: ["accents", "espaces dans les noms", "caractères spéciaux", "slug", "normaliser"],
    aliases: ["clean filenames", "sanitize filenames"],
    status: "planned",
    capabilities: ["local", "batch", "destructive"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-organize",
    name: "Organiser un dossier",
    description: "Ranger automatiquement les fichiers par extension, par date ou par type.",
    category: "files",
    icon: "FolderTree",
    keywords: [
      "ranger", "organiser", "classer", "par extension", "par date",
      "trier mon dossier téléchargements", "mettre de l'ordre",
    ],
    aliases: ["organize folder", "sort files"],
    status: "planned",
    capabilities: ["local", "batch", "long-running", "destructive"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "folder-size",
    name: "Analyser la taille d'un dossier",
    description: "Voir ce qui occupe réellement l'espace disque, dossier par dossier.",
    category: "files",
    icon: "HardDrive",
    keywords: [
      "taille", "espace disque", "qu'est-ce qui prend de la place",
      "gros fichiers", "disque plein", "analyser",
    ],
    aliases: ["folder size", "disk usage", "disk analyzer"],
    status: "planned",
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-secure-delete",
    name: "Suppression sécurisée",
    description: "Écraser un fichier avant suppression pour le rendre irrécupérable.",
    category: "files",
    alsoIn: ["security"],
    icon: "Trash2",
    keywords: [
      "effacer définitivement", "suppression sécurisée", "irrécupérable",
      "shred", "détruire un fichier", "vraiment supprimer",
    ],
    aliases: ["secure delete", "shred", "wipe file"],
    status: "planned",
    capabilities: ["local", "destructive", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
    note: "Sur SSD, l'écrasement n'offre pas les mêmes garanties que sur disque mécanique.",
  },
]);
