import { defineTools, IN, OUT } from "./shared";

export const fileTools = defineTools([
  {
    id: "archive-create",
    name: "Créer une archive",
    description: "Compresser des fichiers ou dossiers en ZIP, 7z, TAR, TAR.GZ ou TAR.XZ, arborescence conservée.",
    category: "files",
    icon: "FolderArchive",
    keywords: [
      "zip", "compresser", "archiver", "7z", "tar", "tar.gz",
      "mettre dans un zip", "regrouper des fichiers",
    ],
    aliases: ["create zip", "compress files", "make archive"],
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.archive(["zip", "7z", "tar", "gz", "xz"])],
    note: "Le 7z produit ici n'est pas chiffré : pour une archive protégée par mot de passe, utilisez « Archive protégée », dont le ZIP AES-256 s'ouvre avec 7-Zip, WinRAR, Keka et l'Explorateur Windows.",
  },
  {
    id: "archive-extract",
    name: "Extraire une archive",
    description: "Décompresser une archive ZIP, 7z, TAR, TAR.GZ ou TAR.XZ vers le dossier de votre choix.",
    category: "files",
    icon: "PackageOpen",
    keywords: ["dézipper", "décompresser", "extraire", "ouvrir un zip", "unzip", "désarchiver"],
    aliases: ["unzip", "extract archive", "decompress"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [{ kind: "archive", extensions: ["zip", "7z", "tar", "gz", "tgz", "xz", "txz"] }],
    outputs: [OUT.data()],
    note: "Aucun fichier n'est écrit hors du dossier choisi : les entrées dont le chemin remonte (« ../ »), les chemins absolus et les liens symboliques sont refusés et listés. Le format RAR n'est pas pris en charge.",
  },
  {
    id: "archive-encrypted",
    name: "Archive protégée par mot de passe",
    description: "Créer ou ouvrir une archive chiffrée par mot de passe.",
    category: "files",
    alsoIn: ["security"],
    icon: "FileLock2",
    keywords: [
      "archive protégée", "zip avec mot de passe", "7z chiffré",
      "protéger des fichiers", "archive sécurisée",
    ],
    aliases: ["encrypted zip", "password protected archive"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(), IN.archive()],
    outputs: [OUT.archive()],
    note: "Chiffrement WinZip AES-256 : l'archive s'ouvre avec 7-Zip, WinRAR, PeaZip, Keka et l'Explorateur Windows. Le « ZipCrypto » historique, cassable en quelques secondes, n'est jamais employé. Les noms de fichiers, eux, restent lisibles sans le mot de passe — c'est une limite du format ZIP.",
  },
  {
    id: "file-hash",
    name: "Calculer une empreinte (hash)",
    description: "Obtenir le SHA-256, SHA-512, SHA-1 ou MD5 d'un ou plusieurs fichiers, quelle que soit leur taille.",
    category: "files",
    alsoIn: ["security", "developer"],
    icon: "Fingerprint",
    keywords: ["hash", "empreinte", "md5", "sha256", "sha1", "checksum", "somme de contrôle"],
    aliases: ["file hash", "checksum", "md5", "sha256"],
    capabilities: ["local", "batch", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
  },
  {
    id: "file-verify-hash",
    name: "Vérifier une empreinte",
    description: "Comparer l'empreinte d'un fichier à celle annoncée par sa source.",
    category: "files",
    alsoIn: ["security"],
    icon: "BadgeCheck",
    keywords: [
      "vérifier", "intégrité", "checksum", "le fichier est-il corrompu",
      "comparer un hash", "authenticité",
    ],
    aliases: ["verify checksum", "check integrity", "hash compare"],
    capabilities: ["local"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.none()],
  },
  {
    id: "file-find-duplicates",
    name: "Trouver les fichiers en double",
    description: "Détecter les doublons d'un dossier par contenu et non par nom.",
    category: "files",
    icon: "CopyMinus",
    keywords: ["doublons", "fichiers identiques", "gagner de la place", "nettoyer", "photos en double"],
    aliases: ["find duplicates", "duplicate finder"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-compare",
    name: "Comparer deux fichiers",
    description: "Vérifier si deux fichiers sont identiques, octet par octet ou ligne par ligne.",
    category: "files",
    icon: "GitCompare",
    keywords: ["comparer", "identiques", "différences", "binaire", "diff de fichiers"],
    aliases: ["compare files", "file diff"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
  },
  {
    id: "file-bulk-rename",
    name: "Renommage en masse",
    description: "Renommer des centaines de fichiers avec un modèle, une numérotation ou une regex.",
    category: "files",
    icon: "PenLine",
    keywords: [
      "renommer", "en masse", "batch rename", "numéroter les fichiers",
      "préfixe", "suffixe", "tous mes fichiers",
    ],
    aliases: ["bulk rename", "batch rename"],
    capabilities: ["local", "batch", "destructive"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-clean-names",
    name: "Nettoyer les noms de fichiers",
    description: "Retirer accents, espaces et caractères problématiques des noms de fichiers.",
    category: "files",
    icon: "Eraser",
    keywords: ["accents", "espaces dans les noms", "caractères spéciaux", "slug", "normaliser"],
    aliases: ["clean filenames", "sanitize filenames"],
    capabilities: ["local", "batch", "destructive"],
    acceptedInputs: [IN.anyFile(), IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "file-organize",
    name: "Organiser un dossier",
    description: "Ranger automatiquement les fichiers par extension, par date ou par type.",
    category: "files",
    icon: "FolderTree",
    keywords: [
      "ranger", "organiser", "classer", "par extension", "par date",
      "trier mon dossier téléchargements", "mettre de l'ordre",
    ],
    aliases: ["organize folder", "sort files"],
    capabilities: ["local", "batch", "long-running", "destructive"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
  },
  {
    id: "folder-size",
    name: "Analyser l'espace d'un dossier",
    description: "Voir ce qui occupe réellement l'espace : plus gros fichiers, plus gros sous-dossiers, répartition par type.",
    category: "files",
    icon: "HardDrive",
    keywords: [
      "taille", "espace disque", "qu'est-ce qui prend de la place",
      "gros fichiers", "disque plein", "analyser",
    ],
    aliases: ["folder size", "disk usage", "disk analyzer", "space analyzer"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
    note: "Seules les métadonnées du système de fichiers sont lues : le contenu des fichiers n'est jamais ouvert. Les dossiers illisibles sont signalés plutôt que comptés à zéro, et les liens symboliques ne sont pas suivis (leur cible serait comptée deux fois).",
  },
  {
    id: "file-secure-delete",
    name: "Suppression sécurisée",
    description: "Écraser le contenu d'un fichier avant de le supprimer, pour rendre sa récupération logicielle très improbable.",
    category: "files",
    alsoIn: ["security"],
    icon: "Trash2",
    keywords: [
      "effacer définitivement", "suppression sécurisée", "irrécupérable",
      "shred", "détruire un fichier", "vraiment supprimer",
    ],
    aliases: ["secure delete", "shred", "wipe file"],
    capabilities: ["local", "destructive", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.none()],
    note: "Effacement logiciel renforcé, pas effacement physique : sur SSD, carte mémoire, Btrfs/ZFS/APFS, ou en présence d'instantanés et de sauvegardes, aucun logiciel ne peut garantir la disparition de toutes les copies antérieures.",
  },
  {
    id: "file-split",
    name: "Diviser un gros fichier",
    description: "Découper un fichier volumineux en morceaux numérotés, avec manifeste de vérification.",
    category: "files",
    icon: "Scissors",
    keywords: [
      "diviser", "découper", "split", "morceaux", "fichier trop gros",
      "clé usb", "fat32", "envoyer un gros fichier", "part001",
    ],
    aliases: ["split file", "file splitter", "diviser un fichier"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.data()],
  },
  {
    id: "file-join",
    name: "Réassembler un fichier",
    description: "Reconstituer un fichier à partir de ses morceaux .part001, avec vérification d'empreinte.",
    category: "files",
    icon: "Combine",
    keywords: [
      "réassembler", "recoller", "join", "fusionner des morceaux",
      "part001", "reconstituer un fichier", "remettre ensemble",
    ],
    aliases: ["join files", "merge parts", "reassemble"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.data()],
  },
  {
    id: "folder-tree",
    name: "Générer l'arborescence d'un dossier",
    description: "Produire l'arborescence en texte d'un dossier, prête à coller dans un README.",
    category: "files",
    alsoIn: ["developer"],
    icon: "FolderTree",
    keywords: [
      "arborescence", "structure", "tree", "plan du dossier",
      "hiérarchie", "readme", "liste des dossiers",
    ],
    aliases: ["folder tree", "directory tree", "arbre des dossiers"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.text()],
  },
  {
    id: "file-info",
    name: "Inspecter un fichier",
    description: "Type réel détecté par signature, cohérence de l'extension, encodage, dates, empreintes et premiers octets.",
    category: "files",
    alsoIn: ["security"],
    icon: "FileSearch",
    keywords: [
      "informations", "propriétés", "détails", "type de fichier", "inspecter",
      "quel format", "mime", "date de création", "c'est quoi ce fichier",
      "magic bytes", "signature", "extension trompeuse", "vrai format",
      "encodage", "bom", "fins de ligne",
    ],
    aliases: ["file info", "file properties", "file details", "inspect file", "magic bytes"],
    capabilities: ["local"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.none()],
    note: "Le type affiché est celui des premiers octets, pas celui de l'extension : un « .jpg » contenant un PNG est signalé comme tel. Rien n'est renommé automatiquement — la correction reste une action que vous demandez.",
  },
  {
    id: "folder-compare",
    name: "Comparer deux dossiers",
    description: "Voir ce qui est identique, modifié, ou présent d'un seul côté entre deux arborescences.",
    category: "files",
    icon: "GitCompareArrows",
    keywords: [
      "comparer dossiers", "diff dossier", "différences entre deux dossiers",
      "qu'est-ce qui a changé", "deux versions d'un dossier", "avant après",
      "vérifier une copie", "sauvegarde à jour",
    ],
    aliases: ["compare folders", "folder diff", "directory compare", "diff directories"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
    note: "Le mode rapide compare type et taille sans rien lire : deux fichiers de même taille y sont dits « probablement identiques ». Seul le mode fiable confirme l'égalité par le contenu — et il ne lit que les fichiers de même taille, une taille différente suffisant à conclure.",
  },
  {
    id: "folder-sync",
    name: "Synchroniser des dossiers",
    description: "Mettre une destination à jour depuis une source, avec plan détaillé avant toute écriture.",
    category: "files",
    icon: "FolderSync",
    keywords: [
      "synchroniser", "miroir", "copier un dossier", "mettre à jour un dossier",
      "sauvegarde disque externe", "clé usb", "recopier", "répliquer",
      "mirror", "rsync",
    ],
    aliases: ["sync folders", "mirror folder", "folder sync", "one-way sync"],
    capabilities: ["local", "long-running", "destructive"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
    note: "Synchronisation à sens unique : la source fait foi, la destination la suit. Rien n'est écrit avant que vous ayez lu le plan. Le mode miroir supprime de la destination ce qui n'existe plus dans la source, et demande une confirmation distincte.",
  },
  {
    id: "file-search",
    name: "Rechercher dans des fichiers",
    description: "Trouver des fichiers par nom, type, taille, date — ou par le texte qu'ils contiennent.",
    category: "files",
    alsoIn: ["text"],
    icon: "SearchCode",
    keywords: [
      "rechercher", "chercher dans fichiers", "trouver un fichier", "grep",
      "retrouver un document", "où est ce fichier", "chercher un mot",
      "recherche de contenu", "par date", "par taille",
    ],
    aliases: ["search files", "find files", "grep", "search in files"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
    note: "Recherche à la demande : FourTout n'indexe rien en fond et ne conserve rien entre deux recherches. La recherche de contenu n'ouvre que ce qui ressemble vraiment à du texte — un binaire n'est jamais interprété comme tel.",
  },
  {
    id: "file-preview",
    name: "Prévisualiser un fichier",
    description: "Ouvrir n'importe quel fichier sans son application : texte, image, PDF, audio, vidéo, archive ou octets bruts.",
    category: "files",
    icon: "Eye",
    keywords: [
      "aperçu", "prévisualiser", "ouvrir sans logiciel", "voir le contenu",
      "quick look", "regarder un fichier", "lire un fichier",
    ],
    aliases: ["preview file", "quick look", "file viewer"],
    capabilities: ["local"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.none()],
    note: "L'aperçu est choisi d'après le contenu réel, pas d'après l'extension. Les fichiers texte volumineux ne sont chargés que partiellement, et l'aperçu le dit.",
  },
  {
    id: "file-hex-edit",
    name: "Éditer en hexadécimal",
    description: "Lire et corriger les octets d'un fichier, fenêtre par fenêtre, sans jamais le charger en entier.",
    category: "files",
    alsoIn: ["developer"],
    icon: "Binary",
    keywords: [
      "hexadécimal", "hex editor", "éditeur hex", "octets", "binaire",
      "modifier des octets", "offset", "ascii", "dump",
    ],
    aliases: ["hex editor", "hex edit", "binary editor"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.data()],
    note: "Éditeur volontairement borné : pas de modèles binaires, pas de script, pas d'insertion ni de suppression d'octets — seulement des corrections en place, qui ne changent jamais la taille du fichier. Par défaut, le résultat est enregistré dans un nouveau fichier.",
  },
  {
    id: "folder-backup",
    name: "Sauvegarder un dossier",
    description: "Copier un dossier avec un manifeste d'empreintes, pour pouvoir vérifier et restaurer plus tard.",
    category: "files",
    alsoIn: ["security"],
    icon: "DatabaseBackup",
    keywords: [
      "sauvegarde", "backup", "copie de sécurité", "archiver mes documents",
      "avant réinstallation", "disque externe", "protéger mes fichiers",
    ],
    aliases: ["backup folder", "create backup"],
    capabilities: ["local", "long-running", "produces-files"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.data()],
    note: "Format transparent : un dossier « donnees » qui reproduit votre arborescence, et un « manifeste.json » lisible. Aucun conteneur propriétaire — même sans FourTout, vos fichiers restent accessibles. Ce n'est pas une sauvegarde versionnée : chaque sauvegarde est une copie complète et datée.",
  },
  {
    id: "folder-restore",
    name: "Restaurer une sauvegarde",
    description: "Vérifier une sauvegarde FourTout, puis la remettre en place sans écraser ce que vous n'avez pas choisi.",
    category: "files",
    alsoIn: ["security"],
    icon: "ArchiveRestore",
    keywords: [
      "restaurer", "récupérer une sauvegarde", "remettre mes fichiers",
      "restore", "revenir en arrière", "vérifier une sauvegarde",
    ],
    aliases: ["restore backup", "verify backup"],
    capabilities: ["local", "long-running", "produces-files"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.data()],
    note: "L'intégrité est vérifiée avant toute écriture : un fichier abîmé dans la sauvegarde est nommé, pas restauré en silence. Restaurer ne supprime jamais rien dans la destination.",
  },
  {
    id: "checksum-manifest",
    name: "Créer un manifeste d'empreintes",
    description: "Produire un fichier .sha256 listant l'empreinte de chaque fichier d'un dossier.",
    category: "files",
    alsoIn: ["security", "developer"],
    icon: "ListChecks",
    keywords: [
      "manifeste", "checksums", "sha256sum", "liste d'empreintes",
      "avant de graver", "avant d'envoyer", "contrôle d'intégrité", "sfv",
    ],
    aliases: ["checksum manifest", "create checksums", "sha256sum"],
    capabilities: ["local", "long-running", "produces-files"],
    acceptedInputs: [IN.folder(), IN.anyFile()],
    outputs: [OUT.text(["sha256", "sha512", "sha1", "md5", "json"])],
    note: "Le format texte produit est celui de sha256sum : il se relit avec les outils du système, sur n'importe quelle machine. MD5 et SHA-1 restent proposés pour vérifier des empreintes anciennes, mais sont signalés comme inadaptés à un usage de sécurité.",
  },
  {
    id: "checksum-verify",
    name: "Vérifier un manifeste d'empreintes",
    description: "Comparer un dossier à un fichier de checksums : intact, modifié, manquant ou illisible, fichier par fichier.",
    category: "files",
    alsoIn: ["security"],
    icon: "ShieldCheck",
    keywords: [
      "vérifier checksums", "contrôler un manifeste", "sha256sum -c",
      "mes fichiers ont-ils changé", "intégrité d'un dossier", "bit rot",
    ],
    aliases: ["verify checksums", "check manifest", "sha256sum -c"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.folder()],
    outputs: [OUT.none()],
    note: "Un manifeste est une donnée, pas une instruction : une entrée qui remonterait hors du dossier vérifié (« ../ », chemin absolu) est refusée et listée, jamais suivie.",
  },
  {
    id: "hmac",
    name: "Calculer un HMAC",
    description: "Signer un texte ou un fichier avec une clé secrète, en HMAC-SHA-256 ou SHA-512.",
    category: "security",
    alsoIn: ["developer", "files"],
    icon: "KeyRound",
    keywords: [
      "hmac", "signature", "clé secrète", "webhook", "api", "authentifier",
      "signer une requête", "code d'authentification de message",
    ],
    aliases: ["hmac", "message authentication code"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.anyFile(false)],
    outputs: [OUT.none()],
    note: "La clé n'est ni enregistrée, ni journalisée, ni ajoutée aux récents : elle sert au calcul et disparaît. Elle est effacée de l'écran dès que vous quittez l'outil.",
  },
  {
    id: "file-compress",
    name: "Compresser un fichier (GZ, XZ)",
    description: "Réduire un fichier seul en .gz ou .xz — sans en faire une archive.",
    category: "files",
    alsoIn: ["converters"],
    icon: "FileArchive",
    keywords: [
      "gzip", "gz", "xz", "compresser un fichier", "lzma",
      "réduire un fichier", "compression", "log volumineux",
    ],
    aliases: ["gzip", "xz compress", "compress file"],
    acceptedInputs: [IN.anyFile(false)],
    outputs: [OUT.archive(["gz", "xz"])],
    capabilities: ["local", "produces-files", "long-running"],
    note: "« .gz » et « .xz » ne contiennent qu'un seul fichier, sans nom de dossier ni arborescence. Pour compresser plusieurs fichiers en conservant leur organisation, utilisez « Créer une archive » et son format TAR.GZ ou TAR.XZ.",
  },
  {
    id: "file-decompress",
    name: "Décompresser un fichier (GZ, XZ)",
    description: "Retrouver le fichier d'origine d'un .gz ou d'un .xz.",
    category: "files",
    alsoIn: ["converters"],
    icon: "FileOutput",
    keywords: [
      "gunzip", "unxz", "ouvrir un .gz", "ouvrir un .xz",
      "extraire un gz", "décompresser un gz", "décompresser un xz",
    ],
    aliases: ["gunzip", "unxz", "decompress file"],
    acceptedInputs: [{ kind: "archive", extensions: ["gz", "xz"] }],
    outputs: [OUT.data()],
    capabilities: ["local", "produces-files", "long-running"],
    note: "Un « .tar.gz » contient une arborescence : passez plutôt par « Extraire une archive », qui la rétablira. Ici, un .tar.gz redonnerait simplement le .tar.",
  },
  {
    id: "archive-inspect",
    name: "Inspecter une archive",
    description: "Lister le contenu d'une archive sans l'extraire : chemins, tailles, taux de compression, entrées suspectes.",
    category: "files",
    icon: "FileSearch2",
    keywords: [
      "voir le contenu d'un zip", "lister une archive", "sans extraire",
      "qu'y a-t-il dedans", "inspecter zip", "contenu 7z", "parcourir une archive",
    ],
    aliases: ["inspect archive", "list archive", "browse archive"],
    capabilities: ["local"],
    acceptedInputs: [{ kind: "archive", extensions: ["zip", "7z", "tar", "gz", "tgz", "xz", "txz"] }],
    outputs: [OUT.none()],
    note: "Rien n'est décompressé : seule la table des matières de l'archive est lue. Les entrées dont le chemin sortirait du dossier d'extraction sont signalées avant même que vous n'envisagiez d'extraire.",
  },
  {
    id: "archive-test",
    name: "Tester une archive",
    description: "Vérifier qu'une archive est intacte en la décompressant entièrement, sans rien écrire sur le disque.",
    category: "files",
    alsoIn: ["security"],
    icon: "PackageCheck",
    keywords: [
      "tester une archive", "archive corrompue", "zip endommagé",
      "vérifier un zip", "téléchargement incomplet", "intégrité archive", "crc",
    ],
    aliases: ["test archive", "verify archive", "check archive"],
    capabilities: ["local", "long-running"],
    acceptedInputs: [{ kind: "archive", extensions: ["zip", "7z", "tar", "gz", "tgz", "xz", "txz"] }],
    outputs: [OUT.none()],
    note: "Le contenu est réellement décompressé et ses sommes de contrôle vérifiées — lister une archive ne prouverait rien, seul son en-tête serait lu. Rien n'est écrit : les octets sont comptés puis jetés.",
  },
]);
