import { defineTools, IN, OUT } from "./shared";

export const imageTools = defineTools([
  {
    id: "image-convert",
    name: "Convertir une image",
    description: "Passer d'un format à un autre : PNG, JPG, WebP. Lecture aussi de GIF, BMP, TIFF, SVG.",
    category: "images",
    alsoIn: ["converters"],
    icon: "Repeat",
    keywords: [
      "convertir", "changer de format", "png en jpg", "jpg en png", "png en webp",
      "jpg en webp", "webp en png", "webp en jpg", "en webp", "webp", "svg en png",
      "gif en png", "bmp", "tiff", "transformer une image", "heic", "avif",
    ],
    aliases: ["convert image", "png to jpg", "jpg to png", "jpg to webp", "webp to png", "image converter"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-compress",
    name: "Compresser une image",
    description: "Réduire le poids d'une image en contrôlant la perte de qualité.",
    category: "images",
    icon: "Minimize2",
    keywords: ["compresser", "compresser photo", "réduire le poids", "alléger", "optimiser", "photo trop lourde", "moins de ko"],
    aliases: ["compress image", "optimize image", "reduce image size"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-resize",
    name: "Redimensionner une image",
    description: "Changer les dimensions en pixels ou en pourcentage, avec ou sans ratio.",
    category: "images",
    icon: "Scaling",
    keywords: ["redimensionner", "changer taille photo", "taille", "agrandir", "rétrécir", "pixels", "largeur", "hauteur", "1920", "1080"],
    aliases: ["resize image", "scale image"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-crop",
    name: "Rogner une image",
    description: "Recadrer visuellement une image, librement ou selon un ratio (1:1, 4:3, 16:9, 3:2).",
    category: "images",
    icon: "Crop",
    keywords: ["recadrer", "rogner", "rogner photo", "couper", "cadrage", "ratio", "carré", "crop"],
    aliases: ["crop image"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-rotate",
    name: "Rotation et miroir",
    description: "Pivoter par quarts de tour et retourner en miroir, avec aperçu immédiat.",
    category: "images",
    icon: "RotateCw",
    keywords: ["pivoter", "tourner", "rotation", "redresser", "photo penchée", "miroir", "retourner", "90 degrés"],
    aliases: ["rotate image", "rotate and flip"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-flip",
    name: "Miroir horizontal ou vertical",
    description: "Retourner une image comme dans un miroir.",
    category: "images",
    icon: "FlipHorizontal2",
    keywords: ["miroir", "retourner", "symétrie", "flip", "inverser"],
    aliases: ["flip image", "mirror image"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-grayscale",
    name: "Noir et blanc",
    description: "Convertir en niveaux de gris, ou en noir et blanc par seuil réglable.",
    category: "images",
    icon: "Contrast",
    keywords: ["noir et blanc", "niveaux de gris", "grayscale", "monochrome", "seuil", "désaturer"],
    aliases: ["grayscale", "black and white"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-adjust",
    name: "Ajuster une image",
    description: "Régler luminosité, contraste, saturation et gamma, avec aperçu en temps réel.",
    category: "images",
    icon: "SlidersHorizontal",
    keywords: ["ajuster", "luminosité", "contraste", "saturation", "gamma", "éclaircir", "assombrir", "corriger"],
    aliases: ["adjust image", "brightness contrast"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-blur",
    name: "Flouter ou pixelliser",
    description: "Masquer une information : flou ou mosaïque, sur toute l'image ou une zone dessinée.",
    category: "images",
    alsoIn: ["security"],
    icon: "Eraser",
    keywords: ["flouter", "flouter capture", "flou", "pixelliser", "pixeliser", "mosaïque", "masquer", "caviarder", "censurer"],
    aliases: ["blur image", "pixelate"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-remove-transparency",
    name: "Supprimer la transparence",
    description: "Aplatir un PNG ou WebP transparent sur un fond uni (blanc, noir ou couleur).",
    category: "images",
    icon: "Square",
    keywords: ["supprimer la transparence", "aplatir", "fond blanc", "fond uni", "enlever alpha", "opaque"],
    aliases: ["remove transparency", "flatten image"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-remove-background",
    name: "Retirer l'arrière-plan",
    description: "Détourer automatiquement le sujet d'une photo et rendre le fond transparent.",
    category: "images",
    alsoIn: ["security"],
    icon: "Scissors",
    keywords: [
      "supprimer arrière plan", "retirer fond image", "fond transparent", "détourer photo",
      "détourage", "enlever le fond", "isoler le sujet", "photo de profil", "remove background",
      "background removal", "png transparent",
    ],
    aliases: ["remove background", "background remover", "cutout", "detourage automatique"],
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png"])],
    note: "Le modèle de détourage s'installe une fois depuis Paramètres → Modèles, puis fonctionne hors ligne : l'image n'est jamais envoyée sur un serveur. Il reconnaît un sujet principal net et détaché ; il se trompe sur les scènes sans sujet évident et sur les détails très fins.",
  },
  {
    id: "image-color-transparent",
    name: "Rendre une couleur transparente",
    description: "Effacer une couleur unie (fond) et la remplacer par de la transparence.",
    category: "images",
    icon: "Sparkles",
    keywords: ["rendre transparent", "détourer", "enlever le fond", "couleur transparente", "fond transparent", "chroma"],
    aliases: ["color to transparent", "remove background color"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png"])],
  },
  {
    id: "image-ocr",
    name: "Extraire le texte d'une image (OCR)",
    description: "Reconnaître le texte d'une image, en français ou en anglais, 100 % en local.",
    category: "images",
    alsoIn: ["text"],
    icon: "ScanText",
    keywords: [
      "ocr", "extraire le texte", "extraire texte photo", "image en texte", "lire le texte",
      "reconnaissance de texte", "numériser", "scanner un texte", "texte depuis image",
    ],
    aliases: ["ocr", "image to text", "extract text"],
    capabilities: ["local", "batch", "long-running"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.text(["txt"])],
  },
  {
    id: "image-add-text",
    name: "Texte sur une image",
    description: "Écrire du texte sur une image : légende, mème, annotation, avec placement au doigt.",
    category: "images",
    icon: "Type",
    keywords: ["texte sur image", "légende", "mème", "écrire", "annoter une photo"],
    aliases: ["add text to image", "meme generator"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },
  {
    id: "image-metadata-read",
    name: "Lire les métadonnées d'une image",
    description: "Afficher EXIF, GPS, appareil photo, date de prise de vue.",
    category: "images",
    icon: "Info",
    keywords: ["exif", "métadonnées", "gps", "où a été prise la photo", "appareil photo", "date de la photo"],
    aliases: ["exif viewer", "image metadata"],
    capabilities: ["local"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.none()],
  },
  {
    id: "image-metadata-strip",
    name: "Supprimer les métadonnées d'une image",
    description: "Effacer EXIF et données GPS avant de partager une photo.",
    category: "images",
    alsoIn: ["security"],
    icon: "EyeOff",
    keywords: [
      "supprimer exif", "enlever exif", "enlever les métadonnées", "anonymiser une photo",
      "retirer le gps", "avant de partager", "vie privée",
    ],
    aliases: ["strip exif", "remove metadata", "anonymiser image"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
  },

  {
    id: "image-batch-convert",
    name: "Conversion d'images par lots",
    description: "Appliquer la même conversion à un dossier entier d'images.",
    category: "images",
    alsoIn: ["converters", "files"],
    icon: "Layers",
    keywords: ["par lots", "en masse", "plusieurs images", "dossier d'images", "batch", "toutes mes photos"],
    aliases: ["batch convert", "bulk image convert"],
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.image(true), IN.folder()],
    outputs: [OUT.image()],
  },
  {
    id: "image-watermark",
    name: "Filigrane sur une image",
    description: "Ajouter un logo ou un texte en filigrane, à l'unité ou par lots.",
    category: "images",
    icon: "Droplets",
    keywords: ["filigrane", "watermark", "logo", "signature", "protéger mes photos"],
    aliases: ["watermark image"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-favicon",
    name: "Générer un favicon",
    description: "Produire un favicon multi-tailles et le fichier .ico depuis une image.",
    category: "images",
    alsoIn: ["developer"],
    icon: "Globe",
    keywords: ["favicon", "icone de site", "ico", "onglet navigateur", "logo site web"],
    aliases: ["favicon generator", "ico"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["ico", "png"])],
  },
  {
    id: "image-icon-sizes",
    name: "Générer plusieurs tailles",
    description: "Exporter d'un coup toutes les tailles d'icônes ou de miniatures utiles.",
    category: "images",
    alsoIn: ["developer"],
    icon: "LayoutGrid",
    keywords: ["tailles", "icônes", "app icon", "miniatures", "thumbnails", "toutes les résolutions"],
    aliases: ["icon generator", "app icon sizes"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png"])],
  },
  {
    id: "color-picker",
    name: "Analyser et convertir une couleur",
    description:
      "Couleurs dominantes d'une image, pipette au pixel près, écritures HEX / RGB / HSL / HSV, et contraste WCAG entre un texte et son fond.",
    category: "images",
    alsoIn: ["developer"],
    icon: "Palette",
    keywords: [
      "palette", "couleurs dominantes", "couleur", "hex", "rgb", "hsl", "hsv",
      "extraire les couleurs", "nuancier", "pipette couleur", "pipette",
      "rgb hex", "hex en rgb", "convertir une couleur", "code couleur",
      "contraste wcag", "contraste", "accessibilite couleur", "ratio de contraste",
      "lisibilite texte", "aa aaa",
    ],
    aliases: [
      "color picker", "hex to rgb", "color converter", "eyedropper",
      "wcag contrast", "contrast checker", "color inspector",
    ],
    capabilities: ["local"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.none()],
  },
  {
    id: "document-perspective",
    name: "Corriger la perspective d'un document",
    description:
      "Redresser la photo d'une feuille prise en biais : placez les quatre coins, FourTout la ramène à un rectangle vu de face.",
    category: "images",
    alsoIn: ["text"],
    icon: "Frame",
    keywords: [
      "corriger perspective", "redresser document", "photo de document", "feuille en biais",
      "photo penchee", "document photographie", "redresser une photo", "quatre coins",
      "scanner avec le telephone", "photo de page", "rectifier", "deformation",
    ],
    aliases: ["perspective correction", "dewarp", "document scanner", "deskew photo"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png", "jpg", "webp"])],
    note: "Les quatre coins se placent à la main : c'est toujours exact, là où une détection automatique se trompe. Les proportions déduites des coins sont approchées — imposez le format A4 ou Lettre pour un résultat exact.",
  },
  {
    id: "scan-clean",
    name: "Nettoyer un scan",
    description:
      "Redresser un document légèrement penché, relever le contraste, blanchir un fond gris ou jauni, passer en niveaux de gris ou en noir et blanc.",
    category: "images",
    alsoIn: ["text"],
    icon: "Sparkles",
    keywords: [
      "nettoyer scan", "nettoyer un document scanne", "redresser un scan", "deskew",
      "scan penche", "fond gris", "papier jauni", "contraste document", "scan illisible",
      "noir et blanc document", "ameliorer un scan", "numerisation sale",
    ],
    aliases: ["clean scan", "deskew", "enhance scan", "document cleanup"],
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg", "webp"])],
    note: "Chaque réglage est facultatif et visible en aperçu avant/après. Le blanchiment ne touche jamais aux pixels sombres : le texte fin garde sa densité.",
  },
  {
    id: "image-compare",
    name: "Comparer deux images",
    description:
      "Voir et mesurer ce qui change entre deux images : côte à côte, en superposition ou en différence, avec pixels différents, PSNR et SSIM.",
    category: "images",
    icon: "Columns2",
    keywords: [
      "comparer images", "comparer deux images", "difference image", "image diff",
      "pixel diff", "psnr", "ssim", "difference entre deux photos", "avant apres",
      "qualite de compression", "ecart entre deux images", "superposition",
      "trouver les differences", "metrique image",
    ],
    aliases: ["compare images", "image diff", "pixel diff", "psnr", "ssim", "image comparison"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png"])],
    note: "Deux images de dimensions différentes ne sont jamais redimensionnées sans votre accord : le rééchantillonnage fabriquerait des écarts absents des fichiers.",
  },
  {
    id: "image-contact-sheet",
    name: "Créer une planche-contact",
    description:
      "Disposer plusieurs images en grille sur une seule feuille, avec le nom de chaque fichier.",
    category: "images",
    icon: "LayoutGrid",
    keywords: [
      "planche contact", "planche-contact", "contact sheet", "grille d'images",
      "mosaique", "vignettes", "assembler des images", "montage photos",
      "catalogue d'images", "plusieurs images sur une page",
    ],
    aliases: ["contact sheet", "photo grid", "thumbnail sheet"],
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image(["png", "jpg"])],
  },
]);
