import { defineTools, IN, OUT } from "./shared";

export const imageTools = defineTools([
  {
    id: "image-convert",
    name: "Convertir une image",
    description: "Passer d'un format à un autre : PNG, JPG, WebP, BMP, AVIF, TIFF.",
    category: "images",
    alsoIn: ["converters"],
    icon: "Repeat",
    keywords: [
      "convertir", "changer de format", "png en jpg", "jpg en png", "en webp",
      "webp", "heic", "avif", "bmp", "tiff", "transformer une image",
    ],
    aliases: ["convert image", "png to jpg", "jpg to webp", "image converter"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-compress",
    name: "Compresser une image",
    description: "Réduire le poids d'une image en contrôlant la perte de qualité.",
    category: "images",
    icon: "Minimize2",
    keywords: ["compresser", "réduire le poids", "alléger", "optimiser", "photo trop lourde", "moins de ko"],
    aliases: ["compress image", "optimize image", "reduce image size"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-resize",
    name: "Redimensionner une image",
    description: "Changer les dimensions en pixels ou en pourcentage, avec ou sans ratio.",
    category: "images",
    icon: "Scaling",
    keywords: ["redimensionner", "taille", "agrandir", "rétrécir", "pixels", "largeur", "hauteur"],
    aliases: ["resize image", "scale image"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-crop",
    name: "Recadrer une image",
    description: "Rogner une image librement ou selon un ratio prédéfini.",
    category: "images",
    icon: "Crop",
    keywords: ["recadrer", "rogner", "couper", "cadrage", "ratio", "carré"],
    aliases: ["crop image"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image()],
  },
  {
    id: "image-rotate",
    name: "Pivoter une image",
    description: "Tourner une image d'un angle libre ou par quarts de tour.",
    category: "images",
    icon: "RotateCw",
    keywords: ["pivoter", "tourner", "rotation", "redresser", "photo penchée"],
    aliases: ["rotate image"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-flip",
    name: "Miroir horizontal ou vertical",
    description: "Retourner une image comme dans un miroir.",
    category: "images",
    icon: "FlipHorizontal2",
    keywords: ["miroir", "retourner", "symétrie", "flip", "inverser"],
    aliases: ["flip image", "mirror image"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-batch-convert",
    name: "Conversion d'images par lots",
    description: "Appliquer la même conversion à un dossier entier d'images.",
    category: "images",
    alsoIn: ["converters", "files"],
    icon: "Layers",
    keywords: ["par lots", "en masse", "plusieurs images", "dossier d'images", "batch", "toutes mes photos"],
    aliases: ["batch convert", "bulk image convert"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.image(true), IN.folder()],
    outputs: [OUT.image()],
  },
  {
    id: "image-metadata-read",
    name: "Lire les métadonnées d'une image",
    description: "Afficher EXIF, GPS, appareil photo, date de prise de vue.",
    category: "images",
    icon: "Info",
    keywords: ["exif", "métadonnées", "gps", "où a été prise la photo", "appareil photo", "date de la photo"],
    aliases: ["exif viewer", "image metadata"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.none()],
  },
  {
    id: "image-metadata-strip",
    name: "Supprimer les métadonnées d'une image",
    description: "Effacer EXIF et données GPS avant de partager une photo.",
    category: "images",
    alsoIn: ["security"],
    icon: "EyeOff",
    keywords: [
      "supprimer exif", "enlever les métadonnées", "anonymiser une photo",
      "retirer le gps", "avant de partager", "vie privée",
    ],
    aliases: ["strip exif", "remove metadata", "anonymiser image"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-watermark",
    name: "Filigrane sur une image",
    description: "Ajouter un logo ou un texte en filigrane, à l'unité ou par lots.",
    category: "images",
    icon: "Droplets",
    keywords: ["filigrane", "watermark", "logo", "signature", "protéger mes photos"],
    aliases: ["watermark image"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.image()],
  },
  {
    id: "image-add-text",
    name: "Texte sur une image",
    description: "Écrire du texte sur une image : légende, mème, annotation.",
    category: "images",
    icon: "Type",
    keywords: ["texte sur image", "légende", "mème", "écrire", "annoter une photo"],
    aliases: ["add text to image", "meme generator"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image()],
  },
  {
    id: "image-favicon",
    name: "Générer un favicon",
    description: "Produire un favicon multi-tailles et le fichier .ico depuis une image.",
    category: "images",
    alsoIn: ["developer"],
    icon: "Globe",
    keywords: ["favicon", "icone de site", "ico", "onglet navigateur", "logo site web"],
    aliases: ["favicon generator", "ico"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["ico", "png"])],
  },
  {
    id: "image-icon-sizes",
    name: "Générer plusieurs tailles",
    description: "Exporter d'un coup toutes les tailles d'icônes ou de miniatures utiles.",
    category: "images",
    alsoIn: ["developer"],
    icon: "LayoutGrid",
    keywords: ["tailles", "icônes", "app icon", "miniatures", "thumbnails", "toutes les résolutions"],
    aliases: ["icon generator", "app icon sizes"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.image()],
    outputs: [OUT.image(["png"])],
  },
  {
    id: "color-picker",
    name: "Couleurs et conversions",
    description: "Choisir une couleur, la pipetter dans une image et convertir HEX, RGB, HSL.",
    category: "images",
    alsoIn: ["developer"],
    icon: "Palette",
    keywords: ["couleur", "hex", "rgb", "hsl", "pipette", "palette", "code couleur"],
    aliases: ["color picker", "hex to rgb", "color converter"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.image(), IN.none()],
    outputs: [OUT.none()],
  },
]);
