import { defineTools, IN, OUT } from "./shared";

export const pdfTools = defineTools([
  {
    id: "pdf-merge",
    name: "Fusionner des PDF",
    description: "Assembler plusieurs PDF en un seul document, dans l'ordre de votre choix.",
    category: "pdf",
    icon: "Combine",
    keywords: ["fusionner", "assembler", "combiner", "regrouper", "joindre", "plusieurs pdf", "un seul pdf"],
    aliases: ["merge pdf", "combine pdf", "concaténer pdf"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.pdf(true)],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-split",
    name: "Séparer un PDF",
    description: "Découper un PDF en plusieurs fichiers selon des intervalles de pages.",
    category: "pdf",
    icon: "Scissors",
    keywords: ["séparer", "découper", "diviser", "couper", "scinder", "en deux"],
    aliases: ["split pdf", "diviser pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-extract-pages",
    name: "Extraire des pages",
    description: "Créer un nouveau PDF à partir d'une sélection de pages.",
    category: "pdf",
    icon: "FileOutput",
    keywords: ["extraire", "sélectionner", "récupérer des pages", "garder certaines pages"],
    aliases: ["extract pages", "pdf page extractor"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-remove-pages",
    name: "Supprimer des pages",
    description: "Retirer définitivement certaines pages d'un PDF.",
    category: "pdf",
    icon: "FileMinus",
    keywords: ["supprimer", "enlever", "retirer des pages", "effacer une page"],
    aliases: ["delete pages", "remove pages pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-reorder-pages",
    name: "Réorganiser les pages",
    description: "Changer l'ordre des pages par glisser-déposer.",
    category: "pdf",
    icon: "ArrowUpDown",
    keywords: ["réorganiser", "ordre", "trier les pages", "déplacer une page", "inverser"],
    aliases: ["reorder pages", "organize pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-rotate",
    name: "Faire pivoter des pages",
    description: "Tourner tout ou partie des pages de 90, 180 ou 270 degrés.",
    category: "pdf",
    icon: "RotateCw",
    keywords: ["pivoter", "tourner", "rotation", "redresser", "page à l'envers"],
    aliases: ["rotate pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-compress",
    name: "Compresser un PDF",
    description: "Réduire le poids d'un PDF en gardant une qualité de lecture correcte.",
    category: "pdf",
    icon: "Minimize2",
    keywords: [
      "compresser", "réduire", "réduire la taille", "alléger", "diminuer le poids",
      "optimiser", "trop lourd", "fichier volumineux", "moins de mo",
    ],
    aliases: ["compress pdf", "reduce pdf size", "optimiser pdf", "pdf trop lourd"],
    status: "planned",
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "images-to-pdf",
    name: "Images vers PDF",
    description: "Transformer une série d'images en un document PDF paginé.",
    category: "pdf",
    alsoIn: ["images", "converters"],
    icon: "FileImage",
    keywords: ["images en pdf", "photos en pdf", "jpg en pdf", "png en pdf", "scanner"],
    aliases: ["image to pdf", "jpg to pdf", "png to pdf"],
    status: "planned",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.image(true)],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-to-images",
    name: "PDF vers images",
    description: "Exporter chaque page d'un PDF en PNG ou JPG.",
    category: "pdf",
    alsoIn: ["images", "converters"],
    icon: "Images",
    keywords: ["pdf en images", "pdf en png", "pdf en jpg", "exporter les pages", "capture des pages"],
    aliases: ["pdf to image", "pdf to jpg", "pdf to png"],
    status: "planned",
    capabilities: ["local", "produces-files", "long-running"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.image(["png", "jpg"])],
  },
  {
    id: "document-to-pdf",
    name: "Document vers PDF",
    description: "Convertir un fichier texte, Markdown ou HTML en PDF.",
    category: "pdf",
    alsoIn: ["text", "converters"],
    icon: "FileType2",
    keywords: ["texte en pdf", "markdown en pdf", "html en pdf", "txt en pdf", "docx en pdf"],
    aliases: ["text to pdf", "markdown to pdf", "html to pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.text()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-add-text",
    name: "Ajouter du texte",
    description: "Écrire du texte sur un PDF pour remplir un formulaire ou annoter.",
    category: "pdf",
    icon: "PenLine",
    keywords: ["écrire", "annoter", "remplir", "formulaire", "commentaire", "texte sur pdf"],
    aliases: ["add text to pdf", "fill pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-add-image",
    name: "Ajouter une image ou signature",
    description: "Insérer une image, un tampon ou une signature à l'endroit voulu.",
    category: "pdf",
    icon: "Signature",
    keywords: ["signer", "signature", "tampon", "logo", "coller une image", "parapher"],
    aliases: ["sign pdf", "add signature", "stamp pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf(), IN.image()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-watermark",
    name: "Ajouter un filigrane",
    description: "Apposer un texte ou une image en filigrane sur toutes les pages.",
    category: "pdf",
    icon: "Droplets",
    keywords: ["filigrane", "watermark", "confidentiel", "marquer", "brouillon"],
    aliases: ["watermark pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-page-numbers",
    name: "Numéroter les pages",
    description: "Ajouter une pagination personnalisable en en-tête ou pied de page.",
    category: "pdf",
    icon: "Hash",
    keywords: ["numéroter", "pagination", "numéros de page", "folio"],
    aliases: ["page numbers", "paginate pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-protect",
    name: "Protéger par mot de passe",
    description: "Chiffrer un PDF pour qu'il ne s'ouvre qu'avec un mot de passe.",
    category: "pdf",
    alsoIn: ["security"],
    icon: "Lock",
    keywords: ["protéger", "mot de passe", "chiffrer", "verrouiller", "sécuriser un pdf"],
    aliases: ["protect pdf", "encrypt pdf", "password pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-unlock",
    name: "Déverrouiller un PDF",
    description: "Retirer la protection d'un PDF dont vous connaissez le mot de passe.",
    category: "pdf",
    alsoIn: ["security"],
    icon: "LockOpen",
    keywords: ["déverrouiller", "enlever le mot de passe", "déprotéger", "décrypter"],
    aliases: ["unlock pdf", "remove pdf password", "decrypt pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
    note: "FourTout ne casse pas les protections : le mot de passe doit être connu.",
  },
  {
    id: "pdf-metadata",
    name: "Métadonnées PDF",
    description: "Lire et modifier titre, auteur, sujet et mots-clés d'un PDF.",
    category: "pdf",
    alsoIn: ["security"],
    icon: "Info",
    keywords: ["métadonnées", "propriétés", "auteur", "titre", "infos du document"],
    aliases: ["pdf metadata", "edit pdf properties"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
  {
    id: "pdf-extract-images",
    name: "Extraire les images d'un PDF",
    description: "Récupérer toutes les images intégrées dans un PDF.",
    category: "pdf",
    alsoIn: ["images"],
    icon: "ImageDown",
    keywords: ["extraire les images", "récupérer les photos", "sortir les images"],
    aliases: ["extract images from pdf"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.image(["png", "jpg"])],
  },
  {
    id: "pdf-extract-text",
    name: "Extraire le texte d'un PDF",
    description: "Récupérer le texte sélectionnable d'un PDF, page par page.",
    category: "pdf",
    alsoIn: ["text"],
    icon: "FileSearch",
    keywords: ["extraire le texte", "copier le texte", "pdf en texte", "récupérer le contenu"],
    aliases: ["pdf to text", "extract text"],
    status: "planned",
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.text(["txt", "md"])],
  },
  {
    id: "ocr-document",
    name: "OCR — texte depuis une image ou un scan",
    description: "Reconnaître le texte d'un document scanné ou d'une photo.",
    category: "pdf",
    alsoIn: ["images", "text"],
    icon: "ScanText",
    keywords: [
      "ocr", "reconnaissance de texte", "scan", "numérisé", "photo en texte",
      "lire un scan", "pdf non sélectionnable", "image en texte",
    ],
    aliases: ["ocr", "optical character recognition", "image to text", "scan to text"],
    status: "planned",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.pdf(), IN.image(true)],
    outputs: [OUT.text(["txt"]), OUT.pdf()],
    note: "Utilisera un moteur OCR local embarqué avec l'application.",
  },
  {
    id: "pdf-compare",
    name: "Comparer deux PDF",
    description: "Mettre en évidence les différences entre deux versions d'un document.",
    category: "pdf",
    alsoIn: ["text"],
    icon: "GitCompare",
    keywords: ["comparer", "différences", "diff", "deux versions", "changements"],
    aliases: ["compare pdf", "pdf diff"],
    status: "planned",
    capabilities: ["local", "long-running"],
    acceptedInputs: [IN.pdf(true)],
    outputs: [OUT.none()],
  },
  {
    id: "pdf-redact",
    name: "Caviarder un PDF",
    description: "Masquer définitivement des zones sensibles, contenu supprimé et non simplement recouvert.",
    category: "pdf",
    alsoIn: ["security"],
    icon: "SquareSlash",
    keywords: ["caviarder", "masquer", "anonymiser", "noircir", "censurer", "données sensibles"],
    aliases: ["redact pdf", "caviardage"],
    status: "planned",
    capabilities: ["local", "produces-files", "destructive"],
    acceptedInputs: [IN.pdf()],
    outputs: [OUT.pdf()],
  },
]);
