import { defineTools, IN, OUT } from "./shared";

export const securityTools = defineTools([
  {
    id: "password-generate",
    name: "Générer un mot de passe",
    description: "Créer des mots de passe forts ou des phrases de passe mémorisables.",
    category: "security",
    alsoIn: ["developer"],
    icon: "KeySquare",
    keywords: [
      "mot de passe", "générer", "aléatoire", "sécurisé", "passphrase",
      "mdp", "password fort", "créer un mot de passe",
    ],
    aliases: ["password generator", "generate password", "passphrase"],
    status: "available",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "password-strength",
    name: "Tester la robustesse d'un mot de passe",
    description: "Estimer le temps nécessaire pour casser un mot de passe, hors ligne.",
    category: "security",
    icon: "ShieldQuestion",
    keywords: [
      "robustesse", "force", "mot de passe solide", "sécurité",
      "est-ce que mon mot de passe est bon", "entropie",
    ],
    aliases: ["password strength", "password checker"],
    status: "available",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
    note: "L'analyse est purement locale : le mot de passe saisi n'est jamais transmis.",
  },
  {
    id: "file-encrypt",
    name: "Chiffrer des fichiers",
    description: "Protéger des fichiers par un mot de passe avec un chiffrement moderne.",
    category: "security",
    icon: "Lock",
    keywords: [
      "chiffrer", "crypter", "protéger", "mot de passe", "aes",
      "confidentiel", "sécuriser un fichier",
    ],
    aliases: ["encrypt file", "file encryption", "aes encrypt"],
    status: "available",
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.data()],
  },
  {
    id: "file-decrypt",
    name: "Déchiffrer des fichiers",
    description: "Retrouver le contenu d'un fichier chiffré avec FourTout.",
    category: "security",
    icon: "LockOpen",
    keywords: ["déchiffrer", "décrypter", "ouvrir un fichier chiffré", "restaurer"],
    aliases: ["decrypt file", "file decryption"],
    status: "available",
    capabilities: ["local", "batch", "produces-files", "long-running"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.data()],
  },
  {
    id: "metadata-strip-any",
    name: "Supprimer les métadonnées d'un fichier",
    description: "Nettoyer auteur, dates, appareil et position avant de partager un document.",
    category: "security",
    alsoIn: ["files"],
    icon: "EyeOff",
    keywords: [
      "métadonnées", "anonymiser", "avant de partager", "vie privée",
      "supprimer l'auteur", "traces", "nettoyer un document",
    ],
    aliases: ["strip metadata", "remove metadata", "anonymize file"],
    status: "available",
    capabilities: ["local", "batch", "produces-files"],
    acceptedInputs: [IN.anyFile()],
    outputs: [OUT.data()],
  },
]);
