import { defineTools, IN, OUT } from "./shared";

export const textTools = defineTools([
  {
    id: "text-statistics",
    name: "Compteur de mots et caractères",
    description: "Mots, caractères, phrases, paragraphes et temps de lecture estimé.",
    category: "text",
    icon: "Calculator",
    keywords: [
      "compter", "nombre de mots", "caractères", "signes", "phrases",
      "temps de lecture", "longueur d'un texte", "statistiques",
    ],
    aliases: ["word count", "character count", "reading time", "compteur de mots"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "text", extensions: ["txt", "md"] }],
    outputs: [OUT.none()],
  },
  {
    id: "text-case",
    name: "Changer la casse",
    description: "MAJUSCULES, minuscules, Première Lettre, camelCase, snake_case, kebab-case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: [
      "majuscules", "minuscules", "casse", "capitaliser", "tout en majuscule",
      "camelcase", "snake case", "kebab case", "title case",
    ],
    aliases: ["uppercase", "lowercase", "change case", "text case"],
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "text-clean",
    name: "Nettoyer un texte",
    description: "Retirer espaces superflus, lignes vides, tabulations et caractères invisibles.",
    category: "text",
    icon: "Eraser",
    keywords: [
      "nettoyer", "espaces", "lignes vides", "tabulations", "trim",
      "supprimer les sauts de ligne", "mise en forme", "texte copié collé",
    ],
    aliases: ["clean text", "trim whitespace", "remove empty lines"],
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "text-find-replace",
    name: "Rechercher et remplacer",
    description: "Remplacer du texte en masse, avec ou sans expression régulière.",
    category: "text",
    icon: "Replace",
    keywords: ["remplacer", "rechercher", "substituer", "regex", "chercher et remplacer"],
    aliases: ["find and replace", "search replace"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-compare",
    name: "Comparer deux textes",
    description: "Voir ligne par ligne ce qui a été ajouté, supprimé ou modifié.",
    category: "text",
    alsoIn: ["developer"],
    icon: "GitCompare",
    keywords: ["comparer", "différences", "diff", "deux versions", "changements"],
    aliases: ["diff", "compare text", "text diff", "comparer deux fichiers texte"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text(true)],
    outputs: [OUT.none()],
  },
  {
    id: "text-deduplicate",
    name: "Supprimer les doublons",
    description: "Ne garder qu'une occurrence de chaque ligne, en option sans tenir compte de la casse.",
    category: "text",
    icon: "CopyMinus",
    keywords: ["doublons", "dédupliquer", "lignes en double", "unique", "supprimer les répétitions"],
    aliases: ["remove duplicates", "dedupe lines", "unique lines"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-sort-lines",
    name: "Trier des lignes",
    description: "Classer des lignes par ordre alphabétique, numérique ou aléatoire.",
    category: "text",
    icon: "ArrowDownAZ",
    keywords: ["trier", "classer", "ordre alphabétique", "liste", "ranger"],
    aliases: ["sort lines", "sort list"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "markdown-convert",
    name: "Markdown ↔ HTML / texte",
    description: "Convertir du Markdown en HTML ou en texte brut, et l'inverse.",
    category: "text",
    alsoIn: ["converters", "developer"],
    icon: "FileCode2",
    keywords: ["markdown", "md", "html", "convertir markdown", "texte brut", "rendu"],
    aliases: ["markdown to html", "html to markdown", "md converter"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "text", extensions: ["md", "html", "txt"] }],
    outputs: [OUT.text(["md", "html", "txt"])],
  },
  {
    id: "text-extract-urls",
    name: "Extraire les URL",
    description: "Récupérer toutes les adresses web contenues dans un texte.",
    category: "text",
    icon: "Link",
    keywords: ["urls", "liens", "adresses web", "extraire les liens", "http"],
    aliases: ["extract urls", "link extractor"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-extract-emails",
    name: "Extraire les adresses e-mail",
    description: "Isoler toutes les adresses e-mail présentes dans un texte.",
    category: "text",
    icon: "AtSign",
    keywords: ["emails", "e-mails", "adresses mail", "extraire les mails", "contacts"],
    aliases: ["extract emails", "email extractor"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-extract-numbers",
    name: "Extraire les nombres",
    description: "Sortir tous les nombres d'un texte et en calculer la somme.",
    category: "text",
    icon: "Sigma",
    keywords: ["nombres", "chiffres", "extraire les montants", "somme", "valeurs"],
    aliases: ["extract numbers", "number extractor"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Générer du faux texte : mots, phrases ou paragraphes.",
    category: "text",
    alsoIn: ["developer"],
    icon: "AlignLeft",
    keywords: ["lorem", "faux texte", "texte de remplissage", "placeholder", "maquette"],
    aliases: ["lorem ipsum", "dummy text", "placeholder text"],
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "text-unicode-normalize",
    name: "Normaliser Unicode",
    description: "Uniformiser l'écriture des accents (NFC, NFD, NFKC, NFKD) entre systèmes.",
    category: "text",
    alsoIn: ["developer"],
    icon: "ScanText",
    keywords: [
      "unicode", "accents", "nfc", "nfd", "nfkc", "nfkd", "normaliser",
      "caractères bizarres", "mac windows accents", "comparaison qui échoue",
    ],
    aliases: ["unicode normalization", "normalize unicode", "nfc nfd"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-line-endings",
    name: "Convertir les fins de ligne",
    description: "Passer de CRLF (Windows) à LF (Unix) et inversement, avec détection préalable.",
    category: "text",
    alsoIn: ["files", "developer"],
    icon: "CornerDownLeft",
    keywords: [
      "crlf", "lf", "fins de ligne", "retour chariot", "windows unix",
      "^M", "dos2unix", "unix2dos", "sauts de ligne",
    ],
    aliases: ["line endings", "crlf to lf", "dos2unix", "unix2dos"],
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "docx-extract",
    name: "Word (DOCX) vers texte, Markdown ou HTML",
    description: "Extraire le contenu d'un document Word : titres, paragraphes, listes et tableaux.",
    category: "text",
    alsoIn: ["converters"],
    icon: "FileType2",
    keywords: [
      "docx", "word", "document word", "extraire le texte d'un word",
      "docx en texte", "docx en html", "docx en markdown", "lire un docx",
    ],
    aliases: ["docx to text", "word to text", "docx to html", "docx to markdown"],
    capabilities: ["local"],
    acceptedInputs: [{ kind: "document", extensions: ["docx"] }],
    outputs: [OUT.text(["txt", "md", "html"])],
    note: "La mise en page complexe (colonnes, images, styles) n'est pas restituée : FourTout extrait le contenu et sa structure.",
  },
  {
    id: "docx-to-pdf",
    name: "Word (DOCX) vers PDF",
    description: "Convertir un document Word en PDF : titres, paragraphes, listes et tableaux simples.",
    category: "text",
    alsoIn: ["pdf", "converters"],
    icon: "FileOutput",
    keywords: ["docx en pdf", "word en pdf", "convertir un word", "document en pdf"],
    aliases: ["docx to pdf", "word to pdf"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [{ kind: "document", extensions: ["docx"] }],
    outputs: [OUT.pdf()],
    note: "FourTout reprend le contenu et sa structure — titres, paragraphes, gras, italique, listes, tableaux simples — mais pas la maquette Word : colonnes, zones flottantes, en-têtes et pieds de page, polices spécifiques et images peuvent différer ou disparaître. Pour un rendu fidèle au pixel, exportez en PDF depuis Word ou LibreOffice.",
  },
  {
    id: "document-compare",
    name: "Comparer deux documents",
    description:
      "Comparer le contenu de deux documents — PDF, Word, texte, Markdown ou HTML — même de formats différents, ligne par ligne et mot par mot.",
    category: "text",
    alsoIn: ["pdf", "files"],
    icon: "FileDiff",
    keywords: [
      "comparer documents", "comparer deux documents", "comparer pdf et word",
      "difference entre deux documents", "diff document", "comparer un docx",
      "deux versions", "qu'est-ce qui a change", "comparer contrats", "collationner",
    ],
    aliases: ["compare documents", "document diff", "compare pdf docx"],
    capabilities: ["local"],
    acceptedInputs: [
      { kind: "document", extensions: ["pdf", "docx", "txt", "md", "markdown", "html", "htm"] },
    ],
    outputs: [OUT.text(["txt", "diff"])],
    note: "La comparaison porte sur le texte, pas sur la mise en page : elle dit ce qui a changé dans le contenu, y compris entre deux formats différents. Un PDF scanné doit d'abord passer par « PDF scanné vers PDF recherchable ».",
  },
  {
    id: "text-encoding-detect",
    name: "Détecter l'encodage d'un fichier texte",
    description:
      "Identifier l'encodage, la marque d'ordre des octets et la convention de fin de ligne d'un fichier, avec le degré de certitude réel.",
    category: "text",
    alsoIn: ["developer", "files"],
    icon: "Binary",
    keywords: [
      "encodage texte", "detecter encodage", "quel encodage", "caracteres bizarres",
      "accents casses", "mojibake", "utf8 ou latin1", "bom", "fin de ligne",
      "fichier illisible", "Ã© au lieu de e accent", "charset",
    ],
    aliases: ["detect encoding", "charset detection", "what encoding", "bom"],
    capabilities: ["local"],
    acceptedInputs: [IN.text(), IN.anyFile(false)],
    outputs: [OUT.none()],
    note: "Hors marque d'ordre des octets, aucun fichier ne déclare son encodage : la détection reste une hypothèse, et FourTout affiche sa certitude réelle plutôt qu'un verdict trompeur.",
  },
  {
    id: "text-encoding-convert",
    name: "Convertir l'encodage d'un fichier texte",
    description:
      "Passer d'un encodage à un autre — UTF-8, UTF-8 avec BOM, UTF-16 LE/BE, Windows-1252, Latin-1 — sans perdre un caractère à votre insu.",
    category: "text",
    alsoIn: ["developer", "files"],
    icon: "ArrowRightLeft",
    keywords: [
      "convertir encodage", "utf16 utf8", "latin1 utf8", "windows 1252 utf8",
      "changer encodage", "reparer les accents", "ansi vers utf8", "iso 8859 1",
      "encoder en utf8", "bom", "transcoder",
    ],
    aliases: ["convert encoding", "utf16 to utf8", "latin1 to utf8", "transcode"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [IN.text(), IN.anyFile(false)],
    outputs: [OUT.text()],
    note: "Si l'encodage de destination ne peut pas écrire certains caractères, la conversion est refusée et les caractères concernés sont listés. Le remplacement n'a lieu que si vous le demandez explicitement.",
  },
  {
    id: "subtitle-edit",
    name: "Modifier des sous-titres",
    description:
      "Convertir entre SRT et WebVTT, décaler les horodatages, fusionner deux fichiers, vérifier et réparer.",
    category: "text",
    alsoIn: ["video", "converters"],
    icon: "Captions",
    keywords: [
      "sous titres", "sous-titres", "srt", "vtt", "webvtt", "srt en vtt",
      "vtt en srt", "decaler sous titres", "synchroniser les sous titres",
      "sous titres en retard", "fusionner sous titres", "reparer srt",
      "normaliser sous titres", "sous titres desynchronises", "chevauchement",
    ],
    aliases: ["subtitles", "srt to vtt", "vtt to srt", "shift subtitles", "merge subtitles", "fix srt"],
    capabilities: ["local", "produces-files"],
    acceptedInputs: [{ kind: "text", extensions: ["srt", "vtt"], multiple: true }],
    outputs: [{ kind: "text", extensions: ["srt", "vtt"] }],
    note: "Ce qui est mécaniquement sûr est corrigé (ordre, numérotation, fins de ligne) ; les chevauchements sont signalés mais jamais raccourcis d'office.",
  },
]);
