import { defineTools, IN, OUT } from "./shared";

export const textTools = defineTools([
  {
    id: "text-statistics",
    name: "Compteur de mots et caractères",
    description: "Mots, caractères, phrases, paragraphes et temps de lecture estimé.",
    category: "text",
    icon: "Calculator",
    keywords: [
      "compter", "nombre de mots", "caractères", "signes", "phrases",
      "temps de lecture", "longueur d'un texte", "statistiques",
    ],
    aliases: ["word count", "character count", "reading time", "compteur de mots"],
    status: "available",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "text", extensions: ["txt", "md"] }],
    outputs: [OUT.none()],
  },
  {
    id: "text-case",
    name: "Changer la casse",
    description: "MAJUSCULES, minuscules, Première Lettre, camelCase, snake_case, kebab-case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: [
      "majuscules", "minuscules", "casse", "capitaliser", "tout en majuscule",
      "camelcase", "snake case", "kebab case", "title case",
    ],
    aliases: ["uppercase", "lowercase", "change case", "text case"],
    status: "available",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "text-clean",
    name: "Nettoyer un texte",
    description: "Retirer espaces superflus, lignes vides, tabulations et caractères invisibles.",
    category: "text",
    icon: "Eraser",
    keywords: [
      "nettoyer", "espaces", "lignes vides", "tabulations", "trim",
      "supprimer les sauts de ligne", "mise en forme", "texte copié collé",
    ],
    aliases: ["clean text", "trim whitespace", "remove empty lines"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
  {
    id: "text-find-replace",
    name: "Rechercher et remplacer",
    description: "Remplacer du texte en masse, avec ou sans expression régulière.",
    category: "text",
    icon: "Replace",
    keywords: ["remplacer", "rechercher", "substituer", "regex", "chercher et remplacer"],
    aliases: ["find and replace", "search replace"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-compare",
    name: "Comparer deux textes",
    description: "Voir ligne par ligne ce qui a été ajouté, supprimé ou modifié.",
    category: "text",
    alsoIn: ["developer"],
    icon: "GitCompare",
    keywords: ["comparer", "différences", "diff", "deux versions", "changements"],
    aliases: ["diff", "compare text", "text diff"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text(true)],
    outputs: [OUT.none()],
  },
  {
    id: "text-deduplicate",
    name: "Supprimer les doublons",
    description: "Ne garder qu'une occurrence de chaque ligne, en option sans tenir compte de la casse.",
    category: "text",
    icon: "CopyMinus",
    keywords: ["doublons", "dédupliquer", "lignes en double", "unique", "supprimer les répétitions"],
    aliases: ["remove duplicates", "dedupe lines", "unique lines"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-sort-lines",
    name: "Trier des lignes",
    description: "Classer des lignes par ordre alphabétique, numérique ou aléatoire.",
    category: "text",
    icon: "ArrowDownAZ",
    keywords: ["trier", "classer", "ordre alphabétique", "liste", "ranger"],
    aliases: ["sort lines", "sort list"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "markdown-convert",
    name: "Markdown ↔ HTML / texte",
    description: "Convertir du Markdown en HTML ou en texte brut, et l'inverse.",
    category: "text",
    alsoIn: ["converters", "developer"],
    icon: "FileCode2",
    keywords: ["markdown", "md", "html", "convertir markdown", "texte brut", "rendu"],
    aliases: ["markdown to html", "html to markdown", "md converter"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), { kind: "text", extensions: ["md", "html", "txt"] }],
    outputs: [OUT.text(["md", "html", "txt"])],
  },
  {
    id: "text-extract-urls",
    name: "Extraire les URL",
    description: "Récupérer toutes les adresses web contenues dans un texte.",
    category: "text",
    icon: "Link",
    keywords: ["urls", "liens", "adresses web", "extraire les liens", "http"],
    aliases: ["extract urls", "link extractor"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-extract-emails",
    name: "Extraire les adresses e-mail",
    description: "Isoler toutes les adresses e-mail présentes dans un texte.",
    category: "text",
    icon: "AtSign",
    keywords: ["emails", "e-mails", "adresses mail", "extraire les mails", "contacts"],
    aliases: ["extract emails", "email extractor"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "text-extract-numbers",
    name: "Extraire les nombres",
    description: "Sortir tous les nombres d'un texte et en calculer la somme.",
    category: "text",
    icon: "Sigma",
    keywords: ["nombres", "chiffres", "extraire les montants", "somme", "valeurs"],
    aliases: ["extract numbers", "number extractor"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none(), IN.text()],
    outputs: [OUT.text()],
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Générer du faux texte : mots, phrases ou paragraphes.",
    category: "text",
    alsoIn: ["developer"],
    icon: "AlignLeft",
    keywords: ["lorem", "faux texte", "texte de remplissage", "placeholder", "maquette"],
    aliases: ["lorem ipsum", "dummy text", "placeholder text"],
    status: "planned",
    capabilities: ["local"],
    acceptedInputs: [IN.none()],
    outputs: [OUT.none()],
  },
]);
