import { defineTools, IN, OUT } from "./shared";

export const videoTools = defineTools([
  {
    id: "video-convert",
    name: "Convertir une vidéo",
    description: "Passer d'un format à un autre : MP4, MKV, WebM, MOV.",
    category: "video",
    alsoIn: ["converters"],
    icon: "Repeat",
    keywords: ["convertir", "changer de format", "mkv en mp4", "avi en mp4", "webm", "mov"],
    aliases: ["convert video", "mkv to mp4", "video converter"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
    note: "Seuls les codecs réellement présents dans le moteur installé sont proposés.",
  },
  {
    id: "video-compress",
    name: "Compresser une vidéo",
    description: "Réduire fortement le poids d'une vidéo en choisissant la qualité cible.",
    category: "video",
    icon: "Minimize2",
    keywords: [
      "compresser", "réduire la taille", "alléger", "trop lourde",
      "envoyer par mail", "moins de mo", "optimiser",
    ],
    aliases: ["compress video", "reduce video size"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-resolution",
    name: "Changer la résolution",
    description: "Passer une vidéo en 1080p, 720p, 480p ou une taille personnalisée.",
    category: "video",
    icon: "Scaling",
    keywords: ["résolution", "1080p", "720p", "480p", "4k", "redimensionner", "définition"],
    aliases: ["resize video", "change resolution", "downscale video"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-trim",
    name: "Découper une vidéo",
    description: "Garder uniquement un extrait, sans réencodage quand c'est possible.",
    category: "video",
    icon: "Scissors",
    keywords: ["découper", "couper", "extrait", "raccourcir", "enlever le début", "supprimer la fin"],
    aliases: ["trim video", "cut video"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-merge",
    name: "Fusionner des vidéos",
    description: "Assembler plusieurs vidéos bout à bout en un seul fichier.",
    category: "video",
    icon: "Combine",
    keywords: ["fusionner", "assembler", "coller", "bout à bout", "réunir des clips"],
    aliases: ["merge video", "concat video", "join video"],
    status: "available",
    capabilities: ["local", "batch", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video(true)],
    outputs: [OUT.video()],
  },
  {
    id: "video-crop",
    name: "Rogner une vidéo",
    description: "Sélectionner visuellement la zone à conserver, avec proportions imposées.",
    category: "video",
    alsoIn: ["images"],
    icon: "Crop",
    keywords: [
      "rogner", "recadrer", "crop", "couper les bords", "format vertical",
      "9:16", "carré", "enlever les bandes noires",
    ],
    aliases: ["crop video", "vertical video", "reframe"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-to-gif",
    name: "Vidéo vers GIF",
    description: "Transformer un extrait vidéo en GIF animé optimisé.",
    category: "video",
    alsoIn: ["images", "converters"],
    icon: "Film",
    keywords: ["gif", "vidéo en gif", "animation", "boucle", "mp4 en gif"],
    aliases: ["video to gif", "mp4 to gif", "gif maker"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.image(["gif"])],
  },
  {
    id: "gif-to-video",
    name: "GIF vers vidéo",
    description: "Convertir un GIF animé en MP4 ou WebM, bien plus léger.",
    category: "video",
    alsoIn: ["images", "converters"],
    icon: "Clapperboard",
    keywords: [
      "gif en vidéo", "gif en mp4", "transformer un gif", "animation en vidéo",
      "gif trop lourd", "convertir un gif",
    ],
    aliases: ["gif to video", "gif to mp4", "gif to webm"],
    status: "available",
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [{ kind: "image", extensions: ["gif"], multiple: false }],
    outputs: [OUT.video(["mp4", "webm"])],
  },
  {
    id: "video-extract-frame",
    name: "Extraire une image d'une vidéo",
    description: "Capturer une frame précise ou des captures à intervalle régulier.",
    category: "video",
    alsoIn: ["images"],
    icon: "Camera",
    keywords: ["capture", "frame", "image d'une vidéo", "screenshot", "photogramme", "miniature"],
    aliases: ["extract frame", "video screenshot", "video to image"],
    status: "available",
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.image(["png", "jpg"])],
  },
  {
    id: "video-speed",
    name: "Changer la vitesse d'une vidéo",
    description: "Créer un accéléré ou un ralenti, audio inclus.",
    category: "video",
    icon: "Gauge",
    keywords: ["vitesse", "accéléré", "ralenti", "timelapse", "slow motion", "plus rapide"],
    aliases: ["video speed", "timelapse", "slow motion"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-rotate",
    name: "Pivoter une vidéo",
    description: "Corriger une vidéo filmée dans le mauvais sens, ou la retourner en miroir.",
    category: "video",
    icon: "RotateCw",
    keywords: [
      "pivoter", "tourner", "rotation", "à l'envers", "filmée à la verticale",
      "redresser", "miroir", "retourner",
    ],
    aliases: ["rotate video", "flip video", "mirror video"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-remove-audio",
    name: "Supprimer le son d'une vidéo",
    description: "Produire une version muette de la vidéo, sans réencoder l'image.",
    category: "video",
    icon: "VolumeX",
    keywords: ["supprimer le son", "muet", "sans audio", "enlever la musique", "couper le son"],
    aliases: ["remove audio", "mute video"],
    status: "available",
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-replace-audio",
    name: "Remplacer la piste audio",
    description: "Remplacer la bande son d'une vidéo, ou lui ajouter une piste supplémentaire.",
    category: "video",
    alsoIn: ["audio"],
    icon: "Music",
    keywords: [
      "remplacer le son", "ajouter une musique", "doublage", "bande son",
      "voix off", "seconde piste audio",
    ],
    aliases: ["replace audio", "add audio track", "dub video"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video(), IN.audio()],
    outputs: [OUT.video()],
    note: "Déposez la vidéo et le fichier audio ensemble.",
  },
  {
    id: "video-volume",
    name: "Régler le volume d'une vidéo",
    description: "Monter ou baisser le son d'une vidéo sans toucher à l'image.",
    category: "video",
    alsoIn: ["audio"],
    icon: "Volume2",
    keywords: [
      "volume", "son trop faible", "son trop fort", "monter le son",
      "baisser le son", "amplifier", "normaliser le volume",
    ],
    aliases: ["video volume", "boost audio", "louder video"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.video()],
  },
  {
    id: "video-add-subtitles",
    name: "Ajouter une piste de sous-titres",
    description: "Attacher un fichier SRT ou VTT à la vidéo, activable dans le lecteur.",
    category: "video",
    alsoIn: ["text"],
    icon: "Subtitles",
    keywords: ["sous-titres", "srt", "vtt", "piste de sous-titres", "softsub", "attacher"],
    aliases: ["add subtitles", "soft subtitles", "mux srt"],
    status: "available",
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.video(), { kind: "text", extensions: ["srt", "vtt", "ass"] }],
    outputs: [OUT.video(["mkv", "webm", "mp4"])],
    note: "Déposez la vidéo et le fichier de sous-titres ensemble.",
  },
  {
    id: "video-burn-subtitles",
    name: "Incruster des sous-titres",
    description: "Graver les sous-titres dans l'image : ils s'affichent sur tous les lecteurs.",
    category: "video",
    alsoIn: ["text"],
    icon: "Captions",
    keywords: [
      "incruster", "hardsub", "graver les sous-titres", "sous-titres dans l'image",
      "srt incrusté", "sous titres visibles partout",
    ],
    aliases: ["burn subtitles", "hardcode srt", "hardsub"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video(), { kind: "text", extensions: ["srt", "vtt", "ass"] }],
    outputs: [OUT.video()],
    note: "Déposez la vidéo et le fichier de sous-titres ensemble.",
  },
  {
    id: "video-extract-subtitles",
    name: "Extraire les sous-titres d'une vidéo",
    description: "Exporter en SRT ou VTT les pistes de sous-titres déjà présentes.",
    category: "video",
    alsoIn: ["text"],
    icon: "FileOutput",
    keywords: [
      "extraire les sous-titres", "récupérer les sous-titres", "sortir le srt",
      "piste de sous-titres", "mkv sous-titres",
    ],
    aliases: ["extract subtitles", "rip subtitles", "demux srt"],
    status: "available",
    capabilities: ["local", "produces-files", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.text(["srt", "vtt"])],
    note: "Seules les pistes textuelles sont exportables ; les pistes graphiques (PGS, DVD) sont des images.",
  },
  {
    id: "video-generate-subtitles",
    name: "Générer les sous-titres d'une vidéo",
    description: "Transcrire automatiquement la parole d'une vidéo, puis exporter ou incruster.",
    category: "video",
    alsoIn: ["audio", "text"],
    icon: "Speech",
    keywords: [
      "générer des sous-titres", "transcription vidéo", "sous-titrer automatiquement",
      "srt automatique", "reconnaissance vocale",
    ],
    aliases: ["auto subtitles", "generate subtitles"],
    status: "available",
    capabilities: ["local", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video()],
    outputs: [OUT.text(["srt", "vtt"])],
    note: "Utilise le modèle de transcription local déjà installé (aucun envoi sur le réseau).",
  },
  {
    id: "video-batch",
    name: "Traitement vidéo par lots",
    description: "Convertir, compresser, redimensionner, pivoter ou extraire l'audio de plusieurs vidéos.",
    category: "video",
    alsoIn: ["files"],
    icon: "Layers",
    keywords: ["par lots", "en masse", "toutes mes vidéos", "dossier", "batch"],
    aliases: ["batch video", "bulk video"],
    status: "available",
    capabilities: ["local", "batch", "produces-files", "long-running", "needs-sidecar"],
    acceptedInputs: [IN.video(true)],
    outputs: [OUT.video()],
  },
]);
